### ISSUE TITLE
Creation of teleTan should log creators id

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#129]
## Where to find the issue

Solution architecture

## Describe the issue
Creation of teleTans is a security risk if they can be created without logging the creator. This may be a low level risk for health authority employees but it is a higher risk with hotline employees.

## Suggested change

When generating a teleTan store the id of the employee, who creates it, together with the teleTan on the verification or portal server. This does not endanger the privacy of the CWA-app User because the additional information is not connected with the App User.
But if an employee creates teleTans for misuse (yes this may happen - the world is sometimes bad) it is possible to verify who created the misused teleTans.

**Comment by tklingbeil** [comment]
The solution architecture document only describes the high-level processes.

Please wait for the documentation and/or code of the Verification Server before making speculations about the specific implementation.

**Comment by SebastianWolf-SAP** [comment]
As @tklingbeil said: At this time this issue is speculation and we will therefore close it. Once a concrete, reproducible issue arises, you can either reopen this issue or create a new one. Thank you for your understanding.


Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
