### ISSUE TITLE
Beacons for special spreading conditions

### ISSUE THREAD

**Issue by FelixSassen** [corona-warn-app/cwa-documentation#144]
Certain environments have strong influence on passing the infection. One example is a high intensity training in a studio (high spreading radius) versus relax yoga (low) radius. Further more the virus will stay for a certain time. Thus a suggested additional feature would be special situation beacons users to model this. I acknowledge that most situations, where this is most useful are currently excluded by imposed restrictions, so this should be considered a suggestion for later improvement, as the general goal of the app is not affected.

Story of use for this suggestion:
A beacon (device running the app) is associated with a training room in a fitness studio changing identifier key on each change of course (infection risk). Training participants register by leaving the phone close to the beacon. Assuming the case of a high intensity training followed by two yoga classes and a participant of the high intensity training receiving a positiv test later. Then the special beacon (after having identified the contact) send the first training identifier key as infected and a scaled down risk for the subsequent yoga class and nothing for the last class as the air should have been exchanged since then. 

Other cases would be:

- settings for taxi drivers, which could set to high risk for normal taxi and low risk with London taxi style separation

- Dance schools, disco, bars, restaurants, ...

I acknowledge, that a decision, which situations are special enough to deserve differentiation should be defined by experts e.g. at the RKI.

**Comment by tens0rfl0w** [comment]
After looking at the 'Solution Architecture' of this project and the documentation of the used 'Exposure Notification' API, I don't see any possibility to implement the mentioned feature(s) in any way that would work out efficiently and provides an adequate accuracy to calculate the 'risk level' of a single person/beacon user. The used API from Apple and Google to calculate/measure the risk potential of a single person/device user has no implementation for stationary beacon devices and is really strict, so there is nearly no possibility to enable that type of communication between stationary and mobile devices while using the given API. In general, the API does not allow to differ between different keys/devices, as this would trigger fundamental privacy concerns and is not needed, so there is no way of telling if a beacon should trigger a general higher risk rate or should behave in a 'normal' way. As a result of that strict behavior, implementation of the mentioned idea(s) would need a separate framework to handle that type of static station devices, that is technically not possible, due to the fact that especially on Apples site, communication between devices is regulated really strict and would need a native OS integration to allow applications to use those interfaces.

Looking at that idea from a non-technical view, I also believe that it is nearly impossible to calculate a accurate 'risk rate' for special 
environments or social events/activities, due to the fact that there are to many external factors
that can't be handled in a 'simple' way when using fixed 'risk rates'.

As nice that idea reads, I think that this is really out of the scope of this project and would need a completely different approach.

**Comment by pdehaye** [comment]
@tens0rfl0w if the limitations only come from Apple/Google (and I think they do), then they are not really limitations, or we should be able to question why they exist

**Comment by tklingbeil** [comment]
I guess those limitations exist because this could (at least theoretically) enable the app to know about the users‘ locations. I understand that your intention is to only process the beacon information within the app - but creating the possibility to link the physical location needs to be prevented.

Apart from that, the app does not have control over the BLE scanning, i.e. it would definitely need to be the EN framework that needs to control this.

**Comment by FelixSassen** [comment]
Thank you for explaining the limitations of the API and the possibilities of breaching privacy protection. The main motivation for suggesting this was, that I trust this project more for data protection, than hand written lists maintained at restaurants, churches, ... with owners having limited experience in privacy protection. (Maybe people need to fear their name appearing in the attendance list of a NGO human rights activist meeting at a conference venue.) 

Having read your comments my suggestion might be simple as a button to temporary collect all contacts. (E.g.: „I am at an indoor choir rehearsal  - store all contacts for the next hour. Not just the close ones“)

If the threshold for collecting contacts is fixed by the API, I understand that this is impossible and I would close this. (Could you let me know?)

**Comment by sventuerpe** [comment]
See also #57 for a similar idea. According to my understanding of the architecture and underlying platform, the following should be possible without violating technical constraints:

An app user obtains a device (or several), installs an instance of CornaWarnApp on it, and dedicates this device to tracing on certain premises. Since app users remain anonymous, any entity can run app instances on as many devices as they can afford. Mobile devices are easily immobilized – just do not move them. 

Effectively, the premises thus become an app user. This user remains indistinguishable from any other within the system and not receive any special treatment. Like any other user the dedicated app instances receive exposure notifications and may send out notifications themselves after obtaining permission from health authorities 

Upon receiving an exposure notification on one of the special devices the operator of the premises contacts the health authorities and explains the situation. After risk assessment the health authority may give them permission to send out exposure notifications to other visitors of the premises.

Notifications would then go to all visitors of the premises within the notification time frame regardless of whether their visit coincided with that of the infected person. Collecting additional information could help to target notifications better, but Apple’s and Google’s contact tracing APIs preclude this by not giving the app access to temporary identifiers at all. 

Premises notifications could, however, be targeted better at the cost of using more devices per location. One could rotate through a set of devices so that each device participates in contact tracing only on certain days or during certain hours. This would implicitly collect information about the time of contact and could limit unnecessary notifications.

All in all, this approach seems possible but not very practical.

**Comment by FelixSassen** [comment]
Thank you for the complete discussion which fully addresses the topic. (Sorry for not spotting that this is a duplicate to 57, which I agree it is.)
Closing with many thanks to the developers.
