### ISSUE TITLE
UI/UX: App title

### ISSUE THREAD

**Issue by user-cb** [corona-warn-app/cwa-documentation#162]
Would you please consider a **different name** for the app. It sounds silly, because Corona-Warn-App is a description, not a title.  Everyone who installs an app on their phone knows that this is an app (what else?). So it is not necessary to have the word app in the title.  It’s like if a book have the word book in the title. 🙃

(And by the way: the app doesn't **warn** you about the virus, it **informs** you about contacts.)

Title reminds me on bad designed German banking/insurance/authority apps. They often have the word app in the title too.

Have a look at other countries‘ apps: Stop Corona, Virus Radar, CovidSafe, Rakning C-19, Covid Tracer, Swiss Covid, Stop Covid ... No word app here.

Also consider the **length** of the name. I guess, the title is to long to fit under the icon on the home screen.

**Comment by tkowark** [comment]
Thank you for your concerns regarding the app title, @user-cb . Since the name is decided by the german government and not the teams doing the technical implementation, can we kindly ask you to use their [respective feedback channels](https://www.bundesregierung.de/breg-en/service/contact)?

Thanks for your understanding,
TK
Corona Warn-App Open Source Team
