### ISSUE TITLE
Codespell report for "cwa-documentation" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [corona-warn-app/cwa-documentation#182]
Similar to the description in the issue [cwa-app-ios#149](https://github.com/corona-warn-app/cwa-app-ios/issues/149) there exists on [fossies.org](https://fossies.org) also a regularly updated  [codespell](https://github.com/codespell-project/codespell) [report](https://fossies.org/features.html#codespell) for "cwa-documentation":

&nbsp;&nbsp;https://fossies.org/linux/test/cwa-documentation-master.tar.gz/codespell.html

Currently only one harmless typo was found ("descibe" -> "describe" in the file "glossary.md").

**Comment by SebastianWolf-SAP** [comment]
Thanks for the report, already fixed by the aforementioned commit.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by jschleus** [comment]
The reports behind the above mentioned URL are done continuously. So I just want point out that in the meantime four small new errors were found.

**Comment by SebastianWolf-SAP** [comment]
Thanks for pointing that out. As it's not automated, such things easily get missed. ;) 3 typos were fixed with 70c1fb3dcc58c5ea036b4e37fdec4556c9e7f589. Synopsys is actually a company name and therefore a false positive. Would be great to be able to mark this one accordingly.

Moreover, please consider teaming up with @dreh23 - there is a PR in the making to integrate spell-checking and related things. See #215.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by jschleus** [comment]
About "Synopsys" I was unsure. It's now excluded and so currently no misspellings are found by the Fossies codespell check.

Yes, I will add a short remark to #215.
