### ISSUE TITLE
Will the Corona App support local health authorities?

### ISSUE THREAD

**Issue by geos-github** [corona-warn-app/cwa-documentation#185]
Local health authorities are conspicuously absent from the User Stories. Nevertheless one keeps reading in the press that the foremost reason for developing the Corona App was to support local health authorities in their laborious contact tracing efforts, reducing the necessary workload. But will the app actually be able to live up to such expectations?
In case of a positive test result local health authorities are informed about the new COVID-19 case. If that person happens to be an app user his or her recorded tokens (I am sure there is a more appropriate term, but I hope 'token' will do) can be uploaded to the central server. Since health authorities (or anyone else) by design have no way of inferring the identity of that person's contacts from the data recorded in the app and since they cannot count on each and everyone of the contacts being automatically informed by their apps (if they are using it) authorities have no choice but to initiate their conventional contact tracing procedures, laboriously identifying and contacting as many of those contacts as they can. Whether or not the infected person has been using the app does not make a difference to them at that point.
Now if the app system works as it is designed, once the infected person's tokens have been uploaded, a certain number of his or her contacts are being informed about the fact that they had an encounter a few days ago with a person who now has been tested positive for COVID-19. What are they supposed to do? They are not and cannot be told by the app who that person is (are they told when that encounter took place so they might make some guess?).
Are those users supposed or even directed to get in touch with their local heath authorities?
Even if so, unless this happens to be the same local authorities who are currently busily tracing the contacts of the person that had been tested positive plus unless they have already worked out the name of the contact who reports in as a reaction to the app notification local health authorities have no means of connecting the dots. In other words, only if they have already established the name of the person reporting in (which assumes that by chance we are dealing with the same local health authority) but have not yet had the time to phone him or her (or did not know the phone number) the message in the app will provide some reduction in the workload for the local authorities at all. However, even in that special case that reduction would probably be quite small since they would have to take their time talking to that person anyway, regardless who contacts whom.
Following the above rationale I cannot see how the Corona App would lead to an increased efficiency for local health authorities and support them in their laborious work. Again, this is not claimed at all in the user stories, but such claims have been widely voiced by other parties (sometimes inappropriately citing the example from South Korea where to my knowledge geolocation and electronic payment data are heavily being used to trace contacts), so it might be a good idea for the the documentation to clarify those aspects.

**Comment by SebastianWolf-SAP** [comment]
Well, what you are describing is in essence one of the disadvantages (from the perspective of the health authorities) of the decentralized system. As we are stating in our [FAQ](https://www.coronawarn.app/en/faq/), there are advantages and disadvantages for both approaches. With a centralized approach the local health authorities could match the app alerts with the ones they already have discovered. But we all know, this centralized approach has trust and data privacy disadvantages and that's why Germany has made the decision to use the decentralized approach. As a consequence, there is also no direct user story with the involvement of the local health authorities...

However, the local health authorities will also benefit considerably from the decentralized approach (if enough device owners install and use the app) - simply by breaking and/or slowing down chains of infection. They will simply have less work to do with tracing people who might be infected if enough people avoid further contact once they have been warned by the app. 

We already clarified that aspect in our FAQ where we clearly state that the app is only one component of several ones: "In addition to the decisive hygiene and behavioural rules to prevent an infection and many other measures, such as the expansion of tests or better contact tracking by health authorities, the Corona-Warn-App is therefore a further element in the fight against the Corona pandemic."

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
