### ISSUE TITLE
Publish a list of Android Phones / ROM versions

### ISSUE THREAD

**Issue by egandro** [corona-warn-app/cwa-documentation#198]
Please publish a list of the Android Phones your team uses for Testing, Debugging and Development.

Please add 

- phone name
- vendor
- ROM version (Android Version, Security patches, ... )
- exact model (there can be differences in CPU / ROM depending on the region the phone intentionally was build for).

As we all know, there can be very ROM / Phone specific issues in Android:

- SQLite Version
- Vendor Modifications
- Vendor Add-ons
- Display size specific issues
- Physical button specific issues
- Bluetooth hardware / Bluetooth stack specific issues we currently don't be aware.

This list can help / benefit to debug such issues.

Please continuously update the list!

**Comment by SebastianWolf-SAP** [comment]
Dear @egandro,

thank you for your request. Unfortunately, we can't compile such as list - especially in the level of detail that you are requesting here. We need to focus on our already communicated deliverables, first and foremost the app itself. 

Once the app is released, the teams will appreciate bug reports containing exactly this information so that issues can be fixed accordingly.

Thank you for your understanding!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by egandro** [comment]
Dear @SebastianWolf-SAP,

> Once the app is released, the teams will appreciate bug reports containing exactly this information so that issues can be fixed accordingly.

from personal experience a "green" list - can really be very very handy in such a project :) 

Since your developers are using the hardware anyway - they can ensure that a specific phone (given my level of detail) works.

You are not only dealing here with well known issues here. There is also Bluetooth involved. Cheap phones can have crazy issues - timeouts or simple not implemented features. 

I really really urge :) Make a "green" now - **in time**. Not during beta. 

it's your choice...
