### ISSUE TITLE
Prevent silent rollout on corporate or managed devices 

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#199]
In order to prevent abnormal usage of corporate and managed devices and wth taking reference to this [risk analysis of tracing apps](https://tracing-risks.com/docs/tracing-risks.pdf) I suggest to prevent automatic or silent rollouts by design.

This could be done with any mandantory user-interaction after installation on initial start e.g. solving of an random math quizzle, random placement of "Agree" or "Let's start" Button or a grace-period for reading before giving consent.

**Comment by SebastianWolf-SAP** [comment]
Transferred to cwa-documentation as it's a request affecting both apps.

**Comment by SebastianWolf-SAP** [comment]
Dear @TomTeeJay,

thanks for bringing up this issue. However, as you can see in our [scoping document](https://github.com/corona-warn-app/cwa-documentation/blob/master/scoping_document.md#onboarding-and-installation) the app already includes an opt-in procedure when the application is launched at the first time. 

Moreover, as you reference the attack scenarios in this paper, only official applications will receive access to the Exposure Notification Framework by Apple and Google, so that a modified version (opt-in removed, other tracking techniques added etc.) of the Corona-Warn-App wouldn't get access to the respective device interface, so no tracking would be possible. 

As opt-in is already mandatory now, we will close this issue accordingly.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
