### ISSUE TITLE
Verification process design decision and rationale

### ISSUE THREAD

**Issue by auschmidt** [corona-warn-app/cwa-documentation#206]
## Your Question

* Architecture Documentation, Verfication Process
* Question:
A specific design decision has been taken to separate duties between Warn-App-Server and Verification Server. An alternative would be such that diagnosis keys are submitted to Verification Server and only verified submissions are forwarded to Warn-App-Server. It would be helpful to explain your design decision in the documentation.

Regards,
AUS

**Comment by mynchau** [comment]
Thank you for your question. We will get back to you as soon as possible. 
Best regards
MC 
Your Corona Warn-App Open Source Team

**Comment by tklingbeil** [comment]
Hi,

Thank you for your question! We have decided for an architecture that separates the concerns of the individual services as much as possible. In your suggestion, we would possibly have the
- GUID/teleTAN, or at least the registration token
- the test result 
- the uploaded diagnosis keys

all in one place.

We have decided to only couple those processes through the TAN in between, so that the CWA-Server does not know about GUIDs/teleTANs, test results (i.e. also some kind of connection to the Lab infrastructure to fetch the results). And the Verification Server does not need to know about diagnosis keys. It just provides an interface to verify a TAN.

If you have a look at some other issues in this repository, you will find that there is even a demand for a stronger separation between the components.
