### ISSUE TITLE
App Name Suggestion: The Emperor's New Virus

### ISSUE THREAD

**Issue by OlliC** [corona-warn-app/cwa-documentation#209]
## Where to find the issue

The app is the issue.
## Describe the issue

Your Corona-Warn-App serves no real use case. It only strenghtens the believe corona is more dangerous than a flu we have every year.
## Suggested change

Rename the app to "The Emperor's New Virus" and add some mini games so it at least serves a purpose by providing some fun.

**Comment by SebastianWolf-SAP** [comment]
We kindly ask you remain professional and avoid comments which violate our [code of conduct](https://github.com/corona-warn-app/cwa-documentation/blob/master/CODE_OF_CONDUCT.md). This is an official warning because of a violation against the behavior "Trolling, insulting or derogatory comments, and personal or political attacks".

And finally, closing this issue as it's almost the same as #162 (except for the mini games).

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
