### ISSUE TITLE
Estimate of false positive rate of Corona-Warn-App?

### ISSUE THREAD

**Issue by geos-github** [corona-warn-app/cwa-documentation#227]
There have been recent press reports about local health authorities in Germany complaining about their work not being supported by the App (which technically is true) and expecting an increased workload through the adoption of the App by the public (cf. eg. https://rp-online.de/panorama/coronavirus/gesundheitsaemter-kritisieren-fehlende-einbindung-bei-corona-app_aid-51583559 or other similar press reports).
In this context it would be interesting to know whether there any estimates about the expected false positive rate of the Corona-Warn-App, in particular with regards to establishing the parameters for the risk score calculation?
Have there been any considerations/estimates how many encounters the average user of the App might have a day which, if the respective contact later reported COVID-19 positive, would constitute a "risky encounter"?
If that figure times the average number of days it takes before a contagious person has been tested positive is large compared to the reproduction number R (i.e. the number of further persons one contagious person infects over the course of the illness) we could directly use it as an estimate for the number of false positives inflicted by the app per uploaded positive test result (this is an upper bound since it assumes that each risky encounter of a given person is with a different individual; more refined calculations and modeling are surely possible).
It would be helpful to get to know about such estimates and considerations as a basis for a fact-based public discussion.

**Comment by pdehaye** [comment]
This issue should also be considered in relation to the attack described in #228.

**Comment by SebastianWolf-SAP** [comment]
We are all aware of challenges regarding the limitations of the used technology, i.e. mobile devices with built-in Bluetooth to trace encounters. Some limitations were already outlined in our [solution architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#limitations). 

The development of the application is accompanied by extensive scientific research how the individual parameters need to be tweaked in order to lower the amount of false warnings. Also after the release of the application, the respective parameters will be updated continuously - as outlined in the [scoping document](https://github.com/corona-warn-app/cwa-documentation/blob/master/scoping_document.md#parameter-settings). You will probably see some additional documentation from our side about this research and how the parameters are determined in detail, but that may still take some time...

Robust numbers can be expected once the application is out and running for quite a while - and of course we will use these numbers for further improvements. Until then, we unfortunately can't provide such details.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
