### ISSUE TITLE
UX App settings FAQ and share on the bottom

### ISSUE THREAD

**Issue by mrascher-cosee** [corona-warn-app/cwa-documentation#231]
## Where to find the issue
Positioning the settings to the bottom might be not a good solution. (Startscreen)

## Suggested change
Apple gives you the opportunity to set the "settings, share and FAQ" to a "Tab-Bar".  In general, use a tab bar to organize information at the app level. A tab bar is a good way to flatten your information hierarchy and provide access to several peer information categories or modes at once.

see: https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/

**Comment by SebastianWolf-SAP** [comment]
Thanks for asking that. We'll take that to our UX/UI designers and ask for a rationale why they chose this approach.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by SebastianWolf-SAP** [comment]
Dear @mrascher-cosee,

we've received feedback from our UX designers. Here's the answer:

- The current approach of one central Home/Overview Screen has received very good feedback in user testing.
- The use of cards instead of small Tab-Bar elements allows to show descriptive content, resulting in a better discoverability of the 3 key features: Risk-calculation, risk-status and test registration/key submission.
- Introducing the Tab-Bar alongside the central Home (e.g. for Settings & FAQs only) would create a more complex information architecture, which the given function-scope of the app does not require and it would draw unnecessary attention at secondary functionalities. 
- We’ll keep your suggestions in mind and if upcoming user-feedback and additional features might require a more comprehensive app structure, we might introduce a Tab-Bar in future releases.

Consequently, we will close this issue. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
