### ISSUE TITLE
Document the estimated effectiveness of this app.

### ISSUE THREAD

**Issue by egandro** [corona-warn-app/cwa-documentation#25]
I am using the numbers of corona dashboard: 

https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4

**2020-05-13**
Total cases: **171.306**
Recovered: **148.700**
Infected: **22.606**

So as far we don't know any estimation for the the unrecorded cases - my assumption is 0 (this can be fixed by assuming the Infected to any higher number you want).

So we have 83.000.000 people in Germany and 22.606 Infected. This is a 83.000.000 / 22.606 = 1 / **3.672** chance of meeting an infected person. (Or 2,7 promille) - assuming an equal distribution.

| Number of installations of the App | Chance 1:x of actually recording an infected person |
| -------- | -------- | 
| 100.000 | 3.047.421 | 
| 200.000 | 1.523.710 | 
| 500.000 | 609.484 | 
| 1.000.000 | 304.742 | 
| 2.000.000 | 152.371 | 
| 2.500.000 | 121.896 | 
| 5.000.000 | 60.948 | 
| 8.000.000 | 38.092 | 
| 10.000.000 | 30.474 | 
| 20.000.000 | 15.237 | 
| 25.000.000 | 12.189 | 
| 50.000.000 | 6.094 | 
| 83.000.000 | 3.671 | 

**Question:** Are we measuring and tracking "the void"?

A 2,7 promille chance if everybody has the app on the phone! This is very very accurate measuring (considering this technology)!

However if we just have 5 mio installation it's 1:60.948 it is only 0,02 promille chance of recording an infected person! 

I assume 0.02 promille this is almost as high as the rate people changing or upgrading their phones on a daily/weekly basis.

Please explain - how effective IS this app?

**Comment by to-fr** [comment]
This is a interesting question.

We're currently at the end of the first wave. 

Although one should not compare the Spanish flu with Corona you can see what can happen in the future (2nd wave).
https://de.wikipedia.org/wiki/Spanische_Grippe

I personally would be very happy measuring only the void!

**Comment by TomTeeJay** [comment]
in addition to this the netzpolitik.org article of limited or non-existing results of the RKI Datenspende App https://netzpolitik.org/2020/erste-auswertung-der-datenspende-app-veroeffentlicht/ and the results of Icelandic Tracing App https://www.technologyreview.com/2020/05/11/1001541/iceland-rakning-c19-covid-contact-tracing/

Though 40% of Icelanders used the Ap it hasn’t helped much. One senior figure said, I quote "the app wasn’t a game changer"

**Comment by egandro** [comment]
> I personally would be very happy measuring only the void!

That is actually very dangerous :( Every smoke detector is doing that 100-x% of the time.

**Comment by to-fr** [comment]
> 
> 
> > I personally would be very happy measuring only the void!
> 
> That is actually very dangerous :( Every smoke detector is doing that 100-x% of the time.

I hate smoke detectors because where I live you have to install them by law. The app on the opposite is voluntary. Smoke detectors cannot be only turned on if you need them. The app on the opposite can be turned on, when the 2nd wave is approaching. I like the app :-)

**Comment by niklas2810** [comment]
> That is actually very dangerous :( Every smoke detector is doing that 100-x% of the time.


To my mind, this thread is a **non-issue** as it has nothing to do with the design of the product, it rather questions the usefulness of the product itself.

**Comment by egandro** [comment]
> opposite can be turned on, when the 2nd wave is approaching. I like the app :-)

So lets assume 100.000 infected in a 2nd wave.

If we have 5 mio installations then the App can detect 1:13778 ... That is 0.07 promill. That's not very efficient.

**Comment by to-fr** [comment]
> 
> 
> > opposite can be turned on, when the 2nd wave is approaching. I like the app :-)
> 
> So lets assume 100.000 infected in a 2nd wave.
> 
> If we have 5 mio installations then the App can detect 1:13778 ... That is 0.07 promill. That's not very efficient.

If  you consider the science magazine as a reliable source:
https://science.sciencemag.org/content/368/6491/eabb6936

:-)

**Comment by egandro** [comment]
> The spread of the virus is also influenced by other factors. Because of that I doubt that this void will be measureable.

Which is beyond of the scope of an App to detect :) like the unrecorded cases. The App can't detect them by design. Check #16

**Comment by egandro** [comment]
> If you consider the science magazine as a reliable source:
> https://science.sciencemag.org/content/368/6491/eabb6936

Again :) #16 - this can't be currently done with this App.

**Comment by s-martin** [comment]
I think that's not the scope of this project here.

German Ministry of Health and their advisors decided that such an app makes sense and should be developed. 

I don't think it makes much sense to discuss the epidemological reasoning behind that app here.

**Comment by to-fr** [comment]
> I don't think it makes much sense to discuss the epidemological reasoning behind that app here.
I agree. Thanks for the hint.

**Comment by MalteJ** [comment]
> German Ministry of Health and their advisors decided that such an app makes sense and should be developed.

and they will be happy to answer the question how effective this app has been.

**Comment by mtbsteve** [comment]
There is a fundamental false assumption in the OP. 
The number of currently detected active/infected cases is rather not relevant for the purpose of this app. 
We can assume that those people are under quarantine or hospitalized. Unless they purposely violate their quarantine obligations you will never meet them in public.

The app will help you to trace back contacts to the ones freshly infected but spreading, not tested, not knowing about their status (yet) in emerging new clusters. 
See the latest outburst in the night club scene in South Korea these days. 

And it will help you to quickly and anonymously inform the person you were in contact with in case when you were infected and not yet knowingly spreading. 

Such kind of anonymous contacts in eg bars cannot be traced by the authorities but this is where this app can help to inform the individual  and prevent further spreading. 

And when people understand that purpose and start using the app, we all will be more safe traveling, visiting concerts, go to soccer games, and other mass events again - all the nice things we may miss right now.

**Comment by egandro** [comment]
> There is a fundamental false assumption in the OP.
> The number of currently detected active/infected cases is rather not relevant for the purpose of this app.

I talked about that.
You don't know what you don't know.
You only know what you know.

We know -given this date - what experts have been detects.

So using this as basis for estimation is a correct approach. If you have better data - just use it!

> And it will help you to quickly and anonymously inform the person you were in contact with in case when you were infected and not yet knowingly spreading.

As you can see in the numbers, this is only possible if you have a high number of installations :)

If not, you can't track contacts. The app is pretty useless if you don't have 30-50 mio installations.

**Comment by Ryuno-Ki** [comment]
> And when people understand that purpose and start using the app, we all will be more safe traveling, visiting concerts, go to soccer games, and other mass events again - all the nice things we may miss right now.

Unless our Minister of interior is declaring the app mandatory to enjoy these things. At that point it will be no longer „voluntarily”. Since F-Droid support is not a priority (see #5), there will be people discriminated or forced into Google/Apple ecosystem.

**Comment by egandro** [comment]
> > German Ministry of Health and their advisors decided that such an app makes sense and should be developed.
> 
> and they will be happy to answer the question how effective this app has been.

l

**Comment by egandro** [comment]
> I think that's not the scope of this project here.

Asking questions about "will this app really do what it should" isn't scope of this project? 

I am afraid :(

**Comment by mtbsteve** [comment]
> Unless our Minister of interior is declaring the app mandatory to enjoy these things. At that point it will be no longer „voluntarily”. Since F-Droid support is not a priority (see #5), there will be people discriminated or forced into Google/Apple ecosystem.

There is no need to make the app mandatory. When people start seeing the value they will use it voluntarily. (my positive assumption) 😀

The underlying LEBT technology from Apple and Google can  support Billions of active users worldwide who are happily  engaged already in the respective app store ecosystems. 
Why care about F-Droid which is only used by a handful of geeks?? Such thing will for sure hamper adoption.

**Comment by to-fr** [comment]
> Asking questions about "will this app really do what it should" isn't scope of this project?

I think this is not the point. Your questions at the beginning 
> Question: Are we measuring and tracking "the void"?
> Please explain - how effective IS this app?

made me think: I didn't understand your question. I can explain how many people have to use the app to archieve the goal of the app to break infection chains but I am not sure if this is what you meant. Perhaps you can clarify your question? Even if the absolute number of traced infections is very low it may be enough to fullfill the goal to break infection chains.

**Comment by egandro** [comment]
> made me think: I didn't understand your question. I can explain how many people have to use the app to archieve the goal of the app to break infection chains but I am not sure if this is what you meant. Perhaps you can clarify your question? Even if the absolute number of traced infections is very low it may be enough to fullfill the goal to break infection chains.

Today (2020-05-13) according to the numbers of infected we have - and again - I can't talk about numbers that we don't have because that are unrecorded cases.

There is (assuming a equal distribution) a 1 : 3.672 probability of meeting an infected person.

The app can't detect unrecorded cases! The app can't even trace back the tree of secondary contacts (see #16).

So if the app records data 97,2% of this events are void data. We know ID 17 met ID 19 but since the probability of having actually somebody infected is so small, you track dust. 

The numbers decrease if the numbers of the installed app are below a certain threshold. For example if you have only 100.000 installations ... one device meeting another device of a user that has (with the given infection number of 2020-05-13) 1 : 3.000.000 probability.

If there is a distribution that is below 30-50 mio devices, you have just an App that is consuming battery (according to math) :)

**Comment by bernd96** [comment]
„Principiis obsta." - Ovid
"Resist the beginnings."

The app serves several purposes:
1. Automate the work the Gesundheitsamt has to do now in case of an infection.
 They have to collect all contact you had the past few weeks and call them one by one, warning them about their risk. If we have 7.000 new cases on a day (e.g. like on 30.03.2020) and each person had 20 contacts during the last week, that would be 140.000 calls. Per day. During this time, each contacted person could infect other persons, which are not recorded cases (2nd-order contact), so we dont have control over the chain.

The apps automates the work of calling the people, and reduces a lot of work.

2. The app also traces contact you would not be aware of, like in public transportation, which reduces the unrecorded cases.

All that serves the main goal: To know and control each infection and quarantine them fast to stop any spreading. If we reach that fast-feedback system, we all can go back to our normal life, because we detect possible "superspreaders" fast enough.

It is a calculation between the energy consumption, the workload of the Callers of Gesundheitsamt and the benefits of controlling each infection spreader.

All in all a really interesting question - thank you!

**Comment by egandro** [comment]
> It is a calculation between the energy consumption, the workload of the Callers of Gesundheitsamt and the benefits of controlling each infection spreader.

As calculated with simple math. Catching potential infected people is only possible if 30-50 mio have installed this app (assumption - they have a compatible smartphone and use it on a daily basis).

You can't catch unrecorded cases - neither you can do a query to secondary contacts #16.

So HOW does this benefit with the workload of the callers? Please describe in math!

**Comment by bernd96** [comment]
Yes. 

> > It is a calculation between the energy consumption, the workload of the Callers of Gesundheitsamt and the benefits of controlling each infection spreader.
> 
> As calculated with simple math. Catching potential infected people is only possible if 30-50 mio have installed this app (assumption - they have a compatible smartphone and use it on a daily basis).

Yes, you are absolutly right. [A study from Oxford ](https://www.research.ox.ac.uk/Article/2020-04-16-digital-contact-tracing-can-slow-or-even-stop-coronavirus-transmission-and-ease-us-out-of-lockdown) did some simulations and concluded we need about 60% of the people to have the app installed, that would be 48 mio.

> You can't catch unrecorded cases - neither you can do a query to secondary contacts #16.
> 
> So HOW does this benefit with the workload of the callers? Please describe in math!

Here you are only partial correct. Yes, you cant catch unrecorded cases in the past, but you can reduce unrecorded cases in the future!
Lets have an infected person who infected 20 people the last 14 days:
Without app: The infected person remembers 10 of them, which get called by the Gesundheitsamt (takes 2-3 days to reach each of them).
So we have 10 unrecorded cases were we dont even have a chance to detect them + eventually 2nd order infections which happend during the 2-3 days where the Gesundheitsamt tried to reach them.

With app: The app can tell all 20 people to get testet (or to get quarantiend). Surely they will also be more careful around other people if they might have been infected.
So we have 10 less unrecorded cases in contrast to without an app.

Of course the real "power" of the app only applies with 2nd-order-tracing, but thats another issue as you said (we dont know yet if it will happen or not).


Yes, maybe is the energy consumption higher than the few thousand cases you can catch additionally with the app. 
But a few thousand which dont "multiply" further can make a hugh difference in terms of constraints, which affect the economy, which generates much more value than the low-energy-bluetooth devices consume. 
Because of the uncertainy here in several parameters it is nearly impossible to say "the app is our livesaver" or "the app is useless" - you can neither prove or disprove it (well, you can try of course - or read papers where [scientists already did the simulations](https://www.research.ox.ac.uk/Article/2020-04-16-digital-contact-tracing-can-slow-or-even-stop-coronavirus-transmission-and-ease-us-out-of-lockdown))
