### ISSUE TITLE
When come the Actually Version Into the play store? 

### ISSUE THREAD

**Issue by Xyz00777** [corona-warn-app/cwa-documentation#267]
You can See from my Screenshot the Actuall Version of the app got uploaded at 12.06., not from Release Day 16.06 and it didnt Got any Update in the since them. Additional ios already have 1.0.2 as Version and not 1.0.0 as in the Google play store. When did we Get the 1.0.2 Version too? 
![Screenshot_20200617-002325](https://user-images.githubusercontent.com/52142054/84834399-8a654480-b031-11ea-9e49-67e013edfacd.jpg)

**Comment by tkowark** [comment]
Dear @Xyz00777 

in fact, the release versions were uploaded earlier as they had to be tested again and allow for some final bugfixes in case we encountered any issues.

Since both apps are developed by two different teams, slight deviations in the version numbers are always possible, especially concerning the last number that denotes minor changes (e.g. some bugs were fixed last minute).

There is no difference between the two versions regarding functionality otherwise.

Best regards,
TK
Corona-Warn-App Open Source Team
