### ISSUE TITLE
Dongle for corona warnings based on ESP32

### ISSUE THREAD

**Issue by williwipfel** [corona-warn-app/cwa-documentation#277]

**Comment by williwipfel** [comment]
Would this make sense for people who do not own a smartfone, but have access to WIFI somewhere?
Think of a small device that one can carry arround like a dosimeter. 
Any suggestions?

**Comment by egandro** [comment]
@williwipfel not that easy possible :(

You need access to a Google API e.g. a VM or an Emulator running Android. The TANs that are generated to send to other devices are generated with a closed source tool.

Google added some limits. e.g. you need to wait some time until you can create the next Token.

This needs to be solved somehow - my idea is to use a REST API to a VM (Android-x86) or an Emulator. I have no POC for this. So have fun about investigating.

**Comment by mh-** [comment]
Have a look at https://simmel.betrusted.io

**Comment by SebastianWolf-SAP** [comment]
Dear @williwipfel, thanks for bringing in this idea. However, we are focussing here on the scope which is outlined in the [respective document](https://github.com/corona-warn-app/cwa-documentation/blob/master/scoping_document.md). Hardware solutions are currently out of scope for this project. Therefore, we need to close this issue here.

Thank you for your understanding!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
