### ISSUE TITLE
Premature closure of issues without having understood their relevance.

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#28]
I've described an issue https://github.com/corona-warn-app/cwa-documentation/issues/23 how this app is discriminating by mixing functions.

The fast notification of test results over non-App users is such an act of discrimination. Such incentives making the voluntary use to a farce. Unfortunately this issue was closed prematurely without understanding the relevance.

**Comment by tkowark** [comment]
The relevance was understood. I closed the issue because besides the user stories, there is no information about how fast / faster notifications are within the app compared to other channels. Hence, speculation. Please create the issue as a question that we can answer, or reopen issues once concrete implementation detail are know.

**Comment by Leseratte10** [comment]
You could say the same thing about "users of the app get the advantage of contact tracing so this is discrimination". Just because the app gives people a feature others don't have doesn't mean that it is discrimination. 

If the app had no "incentive", no feature, then it would be useless and would not do anything.
