### ISSUE TITLE
Internet Connection Error While WLAN and Mobile Data are On

### ISSUE THREAD

**Issue by bernd00** [corona-warn-app/cwa-documentation#284]
<!--
I use a Galaxy S5 (SM-G900F) and Android 6.0.1. When both WLAN and Mobile Data are on, I get an error message "Internet not available". Solution: Turn one off WLAN, or Mobile Data.

**Comment by tkowark** [comment]
Could you kindly provide more details on that issue? If it's specific to one of the app versions, we'll move it there.

**Comment by SebastianWolf-SAP** [comment]
Thanks for opening this issue, @bernd00. Thank you for your understanding that we can't process this issue without further information. If you are having troubles with the app, please call the hotline at +498007540001 first. If you are sure that this is a bug in the software itself, please open another ticket explaining how to reproduce the issue so that we can follow up. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
