### ISSUE TITLE
What features are planned for future releases?

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-documentation#286]
The SAP maintainer @tkowark mentioned planned feature for future releases. It'd be great to know which features are being planned and implemented. Is there information about this somewhere? Is it in the scoping docs, if so where? If not, please tell us what you're working on so that the community can give feedback.

> Thanks for the pointer @ironjan . We're looking into both issues. But please note that main priorities right now are bug fixes and implementing planned features for the next releases. If we can reduce size along that path, we'll, of course, do that, but it is currently not a top priority.
_Originally posted by @tkowark in https://github.com/corona-warn-app/cwa-app-android/issues/527#issuecomment-645258420_

**Comment by SebastianWolf-SAP** [comment]
Thanks for bringing that up, @corneliusroemer. Unfortunately, there is no _complete_ public backlog and to our knowledge such a public overview is currently neither planned nor possible due to several constraints. As you know we are working in a highly dynamic setup with a lot of different parties. Decisions are made pretty fast and could also change pretty fast. So thank you for your understanding that we can only communicate a few of these planned extensions where we more or less know that they are coming. But as it's also not sure to say with which release, we need to stick to the procedure as we do it right now. We are evaluating whether this can change, but it's currently very unlikely. Therefore, we need to close that issue here.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment]
Maintainers, please stop singling me out in responses. I may report issues, but I'm not the only person concerned. I'm part of a large community.

I consider it essential that the community, which is advertised as a big part of this project, knows at least in part what features are being considered so that they can give feedback.

This issue should only be closed if you regularly publish a list of features you are working on. What's so difficult about that? Surely you track features internally, your PMs must have access to something. You could just copy/paste that here.

**Comment by cfritzsche** [comment]
Minimal Roadmap hier: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html unter der Frage „Wie die Corona-Warn-App weiterentwickelt wird“ wird über Erfassung des Symptombeginns und freiwillige statistische Meldung für wissenschaftliche Begleitung ans RKI gesprochen.

**Comment by corneliusroemer** [comment]
@cfritzsche thanks this is a good start! Based on this, I have a more general question re community involvement #301
