### ISSUE TITLE
[SECURITY] SDK attack + process issue

### ISSUE THREAD

**Issue by pdehaye** [corona-warn-app/cwa-documentation#308]
In #228 I tried to explain a new type of attack by tampering with the Associated Encrypted Metadata to mess up with the Bluetooth signal strength reading. 

@SebastianWolf-SAP very quickly re-directed me to Apple and Google, as he considered issues at the Bluetooth layer outside of the scope of this project. I think this is a mistake, for the reasons explained here:
https://github.com/corona-warn-app/cwa-documentation/issues/228#issuecomment-643590914

This is a process issue with the deployment of an app based on the Google and Apple Exposure Notification framework, and it is not new. It is also present in the ongoing deployment of the Swiss app. As explained in https://github.com/corona-warn-app/cwa-documentation/issues/228#issuecomment-643590914, the core mistake is in assuming a nice layered structure to the whole system. 

Unfortunately this mental model is wrong. In [joint work with Joel Reardon](https://arxiv.org/abs/2006.10719) (University of Calgary), we show the consequence: a catastrophic failure of the security model by considering a specific type of attack vectors, namely apps with extensive Bluetooth permissions (or SDKs facilitating the construction of such apps). 

This article is written with the perspective of the Swiss deployment, but it would be equally applicable to the deployment of CoronaWarn, it seems. 

I am assuming the best course of action from here would _not_ be to write a GitHub issue, but to read the official documentation by those who intend to deploy the app (like the Data Protection Impact Assessment), and to contact competent authorities. Unfortunately I do not read German, so at best I can commit to helping those who do who might want to take this further. 

(Note: this should really be two separate issues (security/process), but the same two issues were blended together in the Swiss project. As a consequence we wrote the paper to address the combination of the two issues. So it feels to me it still makes sense to submit a combined issue here)

**Comment by mh-** [comment]
@pdehaye Wow, you have produced a lot of text in this context recently, I wasn't able to read it all.

The words "catastrophic failure" are a bold statement - so maybe you could explain how I could handle the problems that I - from the point of view of an attacker - seem to face:

a) Flipping bits in (unknown) plain text

You repeatedly mentioned that AEM is not authenticated, and therefore I could - within a re-play attack - flip bits of the "TX Power" byte, which is encoded as a signed 8 bit integer. I would want to _decrease_ the plaintext value, because - as explained in b) - I don't have a fleet of high-powered transmitters, and if I succeed, the receiver would later think that the attenuation was lower than in reality --> the estimated distance was shorter than in reality.
Now I have these options:
- flip bit `10000000` - this would change the sign of the value; since the original value is likely negative, now I have a much larger value - not desired.
- flip bit `01000000` - this would either decrease the value by 64, or increase the value by 64, but I don't know what it will do, since I don't know the original value
- flip bit `00100000` - this would either decrease the value by 32, or increase the value by 32, but I don't know what it will do, since I don't know the original value 
- flip bit `00010000` - this would either decrease the value by 16, or increase the value by 16, but I don't know what it will do, since I don't know the original value
- flip bit `00001000` - this would either decrease the value by 8, or increase the value by 8, but I don't know what it will do, since I don't know the original value 
- flip bit `00000100` - this would either decrease the value by 4, or increase the value by 4, but I don't know what it will do, since I don't know the original value
- flip bit `00000010` - this would either decrease the value by 2, or increase the value by 2, but I don't know what it will do, since I don't know the original value
- flip bit `00000001` - this would either decrease the value by 1, or increase the value by 1, but I don't know what it will do, since I don't know the original value

So which bits should I flip? I'm somewhat afraid that if I decrease the "TX power" value below the  received RSSI, the receiver might actually detect my manipulation and simply discard my modified packet.

b) Building a "bot network" of relay-attack beacon receivers and senders

- I tried iOS SDKs, but recently they don't see EN beacons anymore, so I have to resort to Android only
- Nobody seems to want to offer this to me as an option in their legitimate SDK, because everyone is afraid that this could be detected too easily
- With making my own SDK for that purpose, which takes a lot of time to reach many devices, I just don't seem to get enough market coverage with those app makers out there. As you wrote, maybe I should pay them more to use my SDK, but that's a large investment, with very questionable outcome, since this will be detected soon. I think I will rather invest in other attacks.

**Comment by pdehaye** [comment]
a) please keep comments to the AEM tampering attack for #228, do not derail the thread
b) 
* 20% of the iOS phones in Switzerland won't have this update. iPhones don't have a majority of the market. Android phones have more complex update cycles. 
* how do you know no one would be willing to offer it? how do you know it would be detected so easily? 
* the point of [the paper](https://arxiv.org/abs/2006.10719) is that those bot networks can convincingly be said to _already_ exist. As for motivations and investments, this is a separate question. It will most likely depend on the motivation of attacker(s) (confusion or monetary gain). In my opinion, it seems likely state-level actors keen to sow confusion would jump start a market of attackers by bankrolling the initial investment of those interested in monetary gain.

**Comment by SebastianWolf-SAP** [comment]
Dear @pdehaye, dear colleagues,

we discussed this and other issues related to the underlying Exposure Notification system and/or the Bluetooth stack. Unfortunately, our message is still the same as in https://github.com/corona-warn-app/cwa-documentation/issues/228#issuecomment-643340245: We can't address these issues.

The reason is simple: We are not bundling the respective libraries/functionality that implement the Exposure Notification system, the Bluetooth stack or any other component which might be affected or play a role in the issue which you are describing. We only use public and well-documented APIs. The underlying components exposing these APIs are within the responsibility of Apple and Google. Consequently, this and other issues also need to be addressed by these two responsible companies.

Following that, we will close this issue as well. Thank you for your understanding.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
