### ISSUE TITLE
"checked your log of collected random IDs 0 times over the past 24 hours"

### ISSUE THREAD

**Issue by martinknechtel** [corona-warn-app/cwa-documentation#311]
I wonder what this text in the iOS settings means, I see "checked your log of collected random IDs 0 times over the past 24 hours" (German: "dein Protokoll mit erfassten zufälligen IDs während der letzten 24 Stunden 0-mal überprüft").

Can you shed some light on that, does this refer to the iOS-to-CWA app communication? Does it mean iOS did not find any other devices in my proximity triggering the CWA app? I have the app 3 days already.

**Comment by martinknechtel** [comment]
Screenshots attached english/german.

![IMG_5013](https://user-images.githubusercontent.com/2546644/85107162-cb19b500-b20d-11ea-99d0-a6f0b219f53d.PNG)

![IMG_5012](https://user-images.githubusercontent.com/2546644/85107177-d240c300-b20d-11ea-8a32-91657d514504.PNG)

**Comment by mh-** [comment]
@martinknechtel This means that the cwa-server did not distribute any "Diagnosis Keys" to the apps so far. Presumably because nobody has reported their infection through this system yet.
Consequently, the app did not hand these Diagnosis Keys to iOS yet for comparison with the beacons (which iOS probably does have detected already). When the app will do this (in the future), iOS will count it and tell you.

See https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date - this will contain a list of dates, as soon Diagnosis Keys will be available, but at the moment it's only "[]"

**Comment by tkowark** [comment]
Thanks for your question @martinknechtel and also the quick answer, @mh- . As this question was also raised in the iOS repo (corona-warn-app/cwa-app-ios#721, corona-warn-app/cwa-app-ios#675), we'll add an FAQ entry for that and only close this issue once the FAQs are updated

**Comment by tkowark** [comment]
In the meantime, we added the question to the FAQs: https://www.coronawarn.app/en/faq/#no_log_check. Thanks again everybody for pointing that out.
