### ISSUE TITLE
[SECURITY] False negative attack

### ISSUE THREAD

**Issue by pdehaye** [corona-warn-app/cwa-documentation#322]
Issue #228 describes how the Tx power metadata can be modified (in a not necessarily fully deliberate way, there is some randomness involved).

The new [`cwa-risk-assessment.md`](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md) file says that:

> All exposures for a diagnosis key that lasted less than 10 minutes in total (regardless of how close the smartphones came during that time) or during which the smartphones were more than 8 meters (73 dB attenuation) apart on average (regardless of how long the exposure lasted) are discarded as harmless.

If an attacker listens to CW app signals and rebroadcasts the beacons with modified metadata, this will imply that the other CW apps will have many more values to average over. Depending on:
* the exact details of this averaging, as well as 
* the exact detailed capabilities discussed in #228, 

it might mean that some exposures are discarded that shouldn't have been. 

I probably could make this more precise if the doc was itself more precise on how the average is calculated and how the thresholding works.

**Comment by pdehaye** [comment]
The [Apple doc](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration) says

> The attenuation (transmission power - RSSI) can vary during an exposure event. Attenuation values >0 are weighted by the duration at each risk level and averaged for the overall duration. The framework measures and calculates this value.

which seems to confirm what is described above.

**Comment by mh-** [comment]
Well, I will leave it to @sventuerpe to ask the obvious questions.

**Comment by SebastianWolf-SAP** [comment]
Dear @pdehaye, dear colleagues,

we discussed this and other issues related to the underlying Exposure Notification system and/or the Bluetooth stack. Unfortunately, our message is still the same as in https://github.com/corona-warn-app/cwa-documentation/issues/228#issuecomment-643340245: We can't address these issues.

The reason is simple: We are not bundling the respective libraries/functionality that implement the Exposure Notification system, the Bluetooth stack or any other component which might be affected or play a role in the issue which you are describing. We only use public and well-documented APIs. The underlying components exposing these APIs are within the responsibility of Apple and Google. Consequently, this and other issues also need to be addressed by these two responsible companies.

Following that, we will close this issue as well. Thank you for your understanding.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
