### ISSUE TITLE
Continued contact tracing after positive test result?

### ISSUE THREAD

**Issue by kaysievers** [corona-warn-app/cwa-documentation#326]
I'm unable to find information about the subject, https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#upload-schedule-for-diagnosis-keys mentions ***negative test*** in figure 5, and ***uploading Diagnosis Keys on subsequent days remains theoretical*** in the later sentence. It isn't clear to me how this is actually handled.

How is the contact tracing handled for a user who has submitted a positive test result?

What happens to future contacts in the 14 days after the positive test?

Are future contacts with other users are matched with the positve result in the past and get notified, or does that only apply to contacts in the past?

**Comment by christian-kirschnick** [comment]
When a positive tested user uploads his keys, he will share his keys once - and hence only warn other people prior to the upload date. Since you have to stay in quarantine afterwards, until you are healthy again, there would be no point to keep tracing & uploading your keys... unless you want to motivate people to break the quarantine.

The documentation theorises about the idea of keeping tracing on until a positive tested user is tested negative again, so you could be sure that no further threat is generated by that person. This would require that all positive tested users are actually getting further tests (until the result is negative) & confirm this in the app - with a questionable additional value, since people will stay in quarantine anyways. Opening this door would lead to a lot of potential for abuse.

**Comment by daimpi** [comment]
Thanks for the Answer christianchristian-kirschnick :)

This brought me to a related question:
TEKs are rolled over every 24h (at 00:00 UTC). In the current implementation: if a user uploads their TEKs at - lets say - 06:00 UTC, can their TEK of the current day be used to generate RPIs which can cause warnings for the rest of the day? Or will any RPIs generated after their TEK is on the server be recognized by the app as non-risk events? Are RPIs recorded together with timestamps by the recording phone? And do TEKs for the current day which are distributed by the server have a timecode that signifies when they were uploaded/became invalid, which would allow the phones to make this distinction?

I’m asking b/c this will probably become more relevant now that we have [padding on the server side](https://github.com/corona-warn-app/cwa-server/pull/609) (i.e. valid TEKs will be more frequently available).

**Comment by mh-** [comment]
@daimpi For the reason you have in mind, the API will not hand over today's TEK to the app. Only TEKs up until yesterday.

**Comment by daimpi** [comment]
@mh- Ok got it.
That o/c solves the problem 🙂.

**Comment by jensjensenjens** [comment]
Just to clarify: Doesn't that introduce lag in warning those who you had contact with on the day of upload? Or is it assumed that the number of contacts on the day of upload is likely to be small anyway, because you probably got some instructions at the test facility that you should stay at home, until you get your test result?

**Comment by christian-kirschnick** [comment]
Ideally we would like to have support for todays key as well, because every day which you did not isolate yourself counts - therefore we already thought of a concept of a second upload, which would happen the day after the initial upload. It did not make it into the first release though, but it is on our radar and a topic we for sure would like to support.

**Comment by tkowark** [comment]
Since the original question is answered and we already have separate wishlist items in place for extensions of the current functionality, we'll close this question as resolved. Thanks again for bringing that up!
