### ISSUE TITLE
More download access

### ISSUE THREAD

**Issue by pilotnbr1** [corona-warn-app/cwa-documentation#342]
The app has only been uploaded to German Playstores. I cannot easily switch the playstore country on my or my wifes phones (android and iphone). I also do not see alternative ways to install outside of a playstore. Cant you please improve the app accessibility?

**Comment by n-thumann** [comment]
The App is already on its way into other countries AppStore and PlayStore (see https://www.coronawarn.app/en/faq/#international & https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-648740442). The installation without theses stores (e.g. via an APK on Android) is technically not possible. ✌️

**Comment by monikaschmitt** [comment]
Hi @pilotnbr1 
Thanks for your question. The first question has been answered by @n-thumann 
WRT the availability outside of Google Play Store, please have a look at the following FAQ on our website: https://www.coronawarn.app/en/faq/#apk
We would therefore close this issue here. 

Thanks a lot
MS
Corona Warn-App Open Source Team

**Comment by pilotnbr1** [comment]
Thanks for the quick responses. I ended up just getting it from apk pure (3rd party app store).
