### ISSUE TITLE
App won't work with iOS 14B1

### ISSUE THREAD

**Issue by git-Shorty** [corona-warn-app/cwa-documentation#347]
Hi, 

just notifying, to have it on agenda. 
Hopefully this app-team will not put aside this issue until iOS 14 is released to the public. Just to realize getting overwhelmed with all the new and altered OS changes, which probably may also could break some well working implementation or workarounds in this app. 
Please face it as early you can. - This App will not help anyone, if it is not useable at iOS 14 release, at some point.
 [](url)
![IMG_0011](https://user-images.githubusercontent.com/43018952/85922872-9ac5bc80-b886-11ea-9e2a-f96340d00cbd.PNG)

Staying aside, to provide debug-resources if needed.

**Comment by christianneu** [comment]
Dear @git-Shorty,

thanks for your issue.

I would close this issue since it is already explained in the FAQ: 

On devices with iOS 14 beta (available since June 22, 2020) Corona-Warn-App currently doesn't start or only displays an error message. The reason is that the Exposure Notification API is not yet available on devices with iOS 14. See the iOS & iPadOS 14 Beta Release Notes.

https://www.coronawarn.app/en/faq/#ios_14_beta

Best Regards
CN
Corona Warn-App Open Source Team
