### ISSUE TITLE
Clarification: Complete Data Deletion on Deinstallation?

### ISSUE THREAD

**Issue by eaglerainbow** [corona-warn-app/cwa-documentation#36]
## Where to find the issue

https://github.com/corona-warn-app/cwa-documentation/blame/cb991f6d5d103130a448ae728919b0109ef0bd06/translations/scoping_document.de.md#L78 states that "all data [of the app] is being deleted" when de-installing it from the device.

At the very right block of https://github.com/corona-warn-app/cwa-documentation/blob/cb991f6d5d103130a448ae728919b0109ef0bd06/translations/user_journey.de.png it is written "ggf.", which roughly means "if applicable".

## Describe the issue
Usually "ggf." indicates that there are conditions where a complete deletion of data would not take place. If that was the case, the statement would be in contradiction with https://github.com/corona-warn-app/cwa-documentation/blame/cb991f6d5d103130a448ae728919b0109ef0bd06/translations/scoping_document.de.md#L78 .

## Suggested change
I assume that all data is expected/planned to be deleted. That is why I suggest to remove the "ggf." from the picture.

## Note
This is similar to #29 but not entirely identical.

**Comment by LukasMasuch** [comment]
Hey @eaglerainbow, Thanks for raising this issue. Unfortunately, from the Exposure Notification API documents it is not yet completely clear if the observed keys will automatically be deleted from device on uninstalling the App. Google currently states that on App uninstallation `the database and keys are deleted from the device` [[Source](https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.1.pdf)]. While Apple mentions that it only `stops scanning and Bluetooth advertising, but diagnosis keys and data remain` [[Source](https://developer.apple.com/documentation/exposurenotification/enmanager/3583729-setexposurenotificationenabled)]. So, we are still waiting for more clarity from Apple/Google on this issue since the app does not have access to delete the observed keys. However, on Apple the observed keys (exposure log) can be deleted from the settings menu at any time.

**Comment by eaglerainbow** [comment]
Thanks. #48 solved this for me.
