### ISSUE TITLE
Why send email for more involved suggestion, rather than opening a Github Issue?

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-documentation#380]
In your [Contribution Guide](https://github.com/corona-warn-app/cwa-documentation/blob/master/CONTRIBUTING.md) you write under "Engaging in Our Project":
*"If you plan to do something more involved, please reach out to us and send an email. This will avoid unnecessary work and surely give you and us a good deal of inspiration."*

Why send an email if we have Github? Isn't it better to have discussions in the open first so that other people can get inspired by whatever someone suggests? Sure, if it's very detailed, irrelevant to others, do email, but why as default pathway? Rather than suggesting: 
*"If you plan to do something more involved, please create an issue outlining your idea and send us a link to it in an email so that we don't miss it!"*?

**Comment by SebastianWolf-SAP** [comment]
The reason is simple and was also outlined in a comment to your question https://github.com/corona-warn-app/cwa-documentation/issues/301#issuecomment-646808560 some weeks ago. 

> We appreciate feedback to all elements of the project. However, additional features or any other content changes beyond fixes need to be aligned on by all partners.

We simply would like to avoid that community members invest a lot of time in new features or other developments which might need to be discarded in case our project partners don't want to integrate these developments. That would lead to frustration which we would like to avoid.

Of course, discussions in issues are also possible and have also heavily been done. ;)

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
