### ISSUE TITLE
Questions on risk assessment and risk states

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-documentation#436]
## Your Question

* Documentation File:
* Line / Paragraph:
* Question:

I have a few questions on cwa risk assessment and risk state.

1) What is the reason why cwa feeds the same key files into ENF for 14 days? 

My current understanding is: although the transmission risk level of a key does not change during these 14 days, but 
(a) the input params to the risk assessment formula (like thresholds, multipliers, lookup tables, ...) might change, 
(b) the total risk score for a specific encounter set depends on the time span from encounter till now, and 
(c) all risk exposures above the thresholds are summed up in the end to yield the total time of exposure.

Is this correct?

2) CVE-2020-24721 regards the RPI resp. the matches as health-related asset; one proposal to fix it is to delete an RPI from ENF database after the first match. 
Would such a change in ENF behaviour have any impact on cwa risk assessment and/or the risk states?

**Comment by hoehleatsu** [comment]
Since nobody seems to answer, here is my current understanding of 1.:

(a) & (c) are correct, but I wouldn't really count (a) as a reasons for doing the computations over all 14 days each time. The main reason is (c). 

About (b): What matters for the encounter is the time between the encounter and the date the person you encountered uploaded their key (the transmission risk level of the encountered person at the day you met with the person). So this will not change over time, i.e. is independent of "now".

Since the current status is a total risk assessment over what encounters you had the last 14 days, allowing risk to accumulate, it's necessary to redo the calculations. In particular it becomes relevant for the summation over the time buckets. See also the blog post [*Risk Scoring in Digital Contact Tracing Apps (using the GAEN framework)*](https://staff.math.su.se/hoehle/blog/2020/09/17/gaen_riskscoring.html) for further mathematical details.

I hope that's helpful.

**Comment by ndegendogo** [comment]
@hoehleatsu Thanks a lot for your explanations, and the reasoning behind the formula.

> allowing risk to accumulate

so at a crowded location with several infected people, obviously their aerosols accumulate, and this increases the risk.

**Comment by MikeMcC399** [comment]
@ndegendogo 
I'm just wondering if this issue can be closed now, since the risk calculation changed with v2 and the blog entry https://www.coronawarn.app/en/blog/2020-12-17-risk-calculation-exposure-notification-framework-2-0/ with the linked documents has provided new information.

Maybe you could check and close this issue if appropriate?

**Comment by ndegendogo** [comment]
@MikeMcC399 yes, you are right, with ENF v2 my question is outdated.

**Still I think not only the diagrams but also the textual description of the new risk formula should be updated.** 
*But I think this was already requested in other tickets.*

*Closing.*

**Comment by MikeMcC399** [comment]
> @ndegendogo 
> **Still I think not only the diagrams but also the textual description of the new risk formula should be updated.**
> _But I think this was already requested in other tickets._

I agree and you are correct that an update has been requested. I renamed the issue which was initially focused on updating for "Onset of Symptoms" to 
"**Out of date Risk Assessment document**" #453.

In https://github.com/corona-warn-app/cwa-documentation/issues/453#issuecomment-753298287 the Open Source Team wrote that the document would be updated, and in the meantime the issue has a Fix 1.12 label attached to it.
