### ISSUE TITLE
Wrong exposures in apartment

### ISSUE THREAD

**Issue by joaocruz04** [corona-warn-app/cwa-documentation#444]
Hello, 

We live in an apartment. My wife gets constant exposure logs, all while being at home. She leaves her phone far away and still get exposure logs (even at night??). I’m the other one with the app at home, and I only get a few exposures, all green. We’re thinking maybe a neighbor is close enough and messing the exposure logs, but I thought you need to be very close for it to say it’s a contact..

Can this be solved somehow?
Thanks

**Comment by Ein-Tim** [comment]
Hey @joaocruz04 

What do you mean with "Exposure logs"? Do you mean theat your wife got a "Red Risk" Encounter and you only get "Green Risk" ones?

**Comment by joaocruz04** [comment]
@Ein-Tim i mean she gets red exposure logs although she doesn’t leave home, and those logs occour mostly at night when we’re all asleep. I’m the only other person at the place with the app, and I only have few contacts and all green. So it’s impossible she could get exposure logs from anyone else but me. And I’m “green”.

**Comment by Ein-Tim** [comment]
@joaocruz04 

> and those logs occour mostly at night when we’re all asleep.

With logs you mean the timestamps which occurs in settings, right? 
This is only the time the App downloads new Data from the Server, so this is not the Time when your wife met someone. 

And your wife never was somewhere where you weren't?

**Comment by joaocruz04** [comment]
No, she’s been staying home the whole time. My only explanation is the proximity factor: since it’s an apartment, could it be any neighbor in the upper or lower floor that has his/her device closer to the floor/roof?

**Comment by daimpi** [comment]
@joaocruz04 your wife is shown a red/increased risk in CWA right? How many contacts does CWA say she had and when did the last contact happen according to CWA? Was the phone of your wife at home for the whole last 14 days? Did you have any visitors at your place in the last 14 days?

**Comment by joaocruz04** [comment]
Yes, she keeps getting new contacts. No visits. The app says most recent contact was two days ago. We’ve been both at home.

**Comment by Ein-Tim** [comment]
@joaocruz04 
As you can see in #422 it is possible (because of a bug) that the days since last Encounter is wrong, so maybe your wife also only had a Low Risk Encounter 2 days ago, and not a High Risk one.

This is only one assumption from my side, I don't know if your wife has done a test but with a Red Risk Screen from CWA I would definitely do so. 
How the App exactly calculated this High Risk Encounter(s) is impossible to know because of the way CWA and ENF are programmed & designed.

**Comment by joaocruz04** [comment]
It makes sense then. Thanks for the feedback @Ein-Tim ! 👍

**Comment by daimpi** [comment]
@joaocruz04 I second what @Ein-Tim said above.

It could very well be that you received some signals through the wall from devices with high sending power (iPhones [are sending](https://github.com/corona-warn-app/cwa-documentation/issues/341) with high tx power). Usually the attenuation in such cases should be high enough though not to trigger "high/red" risk encounters but only "low/green" ones (but as @Ein-Tim said: the day since the last encounter unfortunately doesn't reliably tell you when the red encounter was in case there is more than one encounter). But if your wife's phone hasn't left the apartment at all in the last 14 days maybe you actually had an very unlucky case in which your neighbor had their phone very close to a thin wall while your wife's phone was on the other side.

**Comment by Ein-Tim** [comment]
So @joaocruz04 if you are happy with the answer(s), could you please close this Issue? 
Thanks & Stay safe

**Comment by heinezen** [comment]
Since all questions here are answered, I will close this issue

----
Corona-Warn-App Open Source Team
