### ISSUE TITLE
Are people in high-risk exposure group contacted in any way?

### ISSUE THREAD

**Issue by wbrydak** [corona-warn-app/cwa-documentation#447]
## What is missing

Hi!
As stated in the issue topic. 
Are people notified of exposure and/or people who are in high-risk group contacted by the Health Authority in any way? 
Are they receiving i.e. text message with token for COVID-19 test?
## Why should it be included

It would clarify the post-notification phase

**Comment by heinezen** [comment]
Hey @wbrydak ,

Do you mean that someone is contacted by an external authority *after* receiving a high risk encounter in the app? 

The following FAQ entries might answer your question:

* https://www.coronawarn.app/en/faq/#risk_info
* https://www.coronawarn.app/en/faq/#central_entity
* https://www.coronawarn.app/en/faq/#anonymous

If this does not answer you question, please make a follow-up comment with more information, so we can find an answer.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@wbrydak 

Since the Risk Analysis is happening on your phone and the Information that you have a High Risk Exposure doesn't leave your phone the Health Authority won't contact you because of CWA. 
It could still be that you are found via "manual" Contact Tracing (e.g. entered name into a Contact List, etc.) from your Health Authority.

**Comment by heinezen** [comment]
@wbrydak I hoope your question was answered with the links I provided. I will close this issue now to mark it as solved.


----
Corona-Warn-App Open Source Team
