### ISSUE TITLE
Feature request: Encounter count change notification

### ISSUE THREAD

**Issue by alongwor** [corona-warn-app/cwa-documentation#448]
This is a feature request as opposed to a bug report.
In the lastest version of the iOS app, notifications seem to have been implemented to remind you to check the app. Better would be notifications if your exposure count changes (up or down). As it stands no, you are not warned if the situation changes, therefore unless checking on a daily basis, no way to identify where your possible exposure was. Warning people would allow for better adoption of behaviour changes etc.
#### Check notification 
![check_notification](https://user-images.githubusercontent.com/6453103/96866527-b8d5af00-146b-11eb-93ad-908c59745dab.jpg)
#### Encounter count
![encounter_count](https://user-images.githubusercontent.com/6453103/96866567-c8ed8e80-146b-11eb-88b3-3838e225349e.jpg)

**Comment by Ein-Tim** [comment]
@alongwor 
Hey the message which you are receiving is buggy, it should only be send if there was no background check in the last 36h. This will be fixed in version 1.5.1
A notification will be send to you if you had a High Risk Encounter, but not if the Encounter was a Low Risk one.

**Comment by alongwor** [comment]
Thanks for the feedback @Ein-Tim. I understand that high risk will give an active notification, I'd consider it a bug if not. I do think there is value in also notifying people of a change, even for low risk exposures.

**Comment by Ein-Tim** [comment]
Okay @alongwor 
Normally, for feauture Requests we have the [Wishlist Repo](https://github.com/corona-warn-app/cwa-wishlist), so thats why I answered your question like I answered it. 

My personal opinion:
Low Risk encounters will get more and more through the winter so I do not think notifying people about these one is a good Idea, maybe as an optionaly Option which is turned off by default.

@abro1i 
Maybe you could transfere this Issue to the CWA Wishlist, so that it is in the right place 👍

**Comment by alongwor** [comment]
I am perfectly with you on the potential for a high frequency of notifications in peak periods and making such a thing optional.
Regarding placement of this issue ticket, I hadn't realised the project structure just followed the links from the main corrona.app page. Knowing now that there is a wishlist repo, I will close here and recreate in the correct place.
