### ISSUE TITLE
Calculating infection risc in case of multiple contacts of same person

### ISSUE THREAD

**Issue by SchwertAs** [corona-warn-app/cwa-documentation#46]
This concerns a new feature. As i have read the evaluation function for the exposed state comes from RKI. This evaluation function should also concern that multiple contacts with the same person increase the infection risk. It also depends on the environment. For instance contacts outside cause much less infection risk than inside contacts.

## Where to find the issue
This feature is new

## Describe the issue
The application should be prepared to evaluate environment facts and to cumulative calculate the exposed risk as probability value. In case of infection all contacts with a significant exposure probability should be informed.

## Suggested change
describe possible input values of the rki Function, describe risk calculation, and decision of IDs to warn

**Comment by egandro** [comment]
Warning IDs in proximity can lead to false positive warnings.

Assume living in a panel building in Eastern Germany - you can easily discover 30+ Bluetooth devices.

You are never in direct contact to any of this person - because walls seams to be very good viral firewalls :)

**Comment by SchwertAs** [comment]
Within buildings the height position of the smartphone is very significant for the exposure risk. Only persons on the same floor level have higher risk to infect the other. This should be concerned in the calculation of exposure risk.

**Comment by egandro** [comment]
> Within buildings the height position of the smartphone is very significant for the exposure risk.

How do you know where you are? :) (from the perspective of the app)

**Comment by TomTeeJay** [comment]
Are there any existing proof of concepts and tests in the real life or are we just splitting a hair about yet to come Apple/Google APIs not tested in any possible indoor and outdoor scenario?

**Comment by SchwertAs** [comment]
The height could be approximated from earth magnetic field. Most smarphones have capability to measure magnetic field strength. Also air pressure is a indicating measure for height position.

**Comment by danielw93** [comment]
"Calculating infection risc in case of multiple contacts of same person"

A privacy preserving implementation of this app would have no possibility to recognize repeat or prolonged contact with the same person because the IDs being broadcast would be changed frequently.
Also this is very dependent on the system functionality provided by Google/Apple.

**Comment by TomTeeJay** [comment]
@SchwertAs 

> The height could be approximated from earth magnetic field.

This is definitely beyond any logical and mathematical possibility. GPS Altitude is already an approximation, leaving inaccurancies of +/- 200 ft (60-70 Meters) caused by inaccurate WGS84 earth model. Without further correction of additinal land based GPS Signals (EGNOS, WAAS or SOPOS) there is no chance of correct GPS altitudes.

Here's an explanation how GPS works and how unfit consumer devices are:
https://ul-fluglehrer.de/blog/files/20160203-tablets-smartphones-gps.html

**Comment by tkowark** [comment]
The upcoming architecture documentation will contain details on the risk score calculation. Would be great if you can review then, and reopen this ticket with a suggestion based on the described implementation.
