### ISSUE TITLE
Impact of default parameters on risk level

### ISSUE THREAD

**Issue by tangomanni** [corona-warn-app/cwa-documentation#460]
Hello,
from the information material I got some insight in the functionality of the CWA. 
There are some assumptions (e.g. course of infectiousness of an infected person) which led to some default parameters used for the calculation of risk level (low, high). With these parameters the current version of the CWA was published.
Question:  Is there any work done to check how the number of low and high risk would change if one or more of these parameters would be changed ? I think this would bake sense to see the impact of one or the other parameter on the risk calculation result.
Kind regards
tangomanni

**Comment by heinezen** [comment]
Hey @tangomanni ,

I have transferred your issue to the cwa-documentation repo because it sounds more like a general question than a feature request.

>  Is there any work done to check how the number of low and high risk would change if one or more of these parameters would be changed ?

The risk score calculation has [its own documentation](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) where the algorithm is outlined and the weight of each parameter is provided. Therefore, it is possible for one to reimplement the algorithm and test it with different parameters. However, I do not know if anyone has done this yet.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
This question has been answered a while ago :)

----
Corona-Warn-App Open Source Team

**Comment by tangomanni** [comment]
Possibly I was misunderstood. A risk score calculation model is available and in the CWA there are some default values (e.g. -73 dB) used. The result is that we see how many people get a high risk warning (= percentage of CWA users). I would like to know what would happen if some of these default values would be changed to other values in a range of plausible values. I will check the current docu again and possibly make a more precise issue.
