### ISSUE TITLE
Bluetooth signal attenuation (dB) into distance (meters): equation and default values of the parameters

### ISSUE THREAD

**Issue by vaggelisdouros** [corona-warn-app/cwa-documentation#484]
Can you provide the formula that translates the bluetooth signal attenuation (measured in dB) into distance (measured in meters)? In multiple cases, it is mentioned that a 73 dB attenuation corresponds to a distance of 8 meters, whereas 55 dB are translated into 1.5 meters, but i have not found the formula that you have used or at least a reference to a paper/textbook. So, please include the values of the receiver/transmitter gain used, the path loss exponent, the frequency (i guess 2.45 GHz), any shadowing effect etc.

---
Internal Tracking ID: EXPOSUREAPP-4449

**Comment by heinezen** [comment]
Hey @vaggelisdouros ,

Thanks for the proposal to include this information. I have asked the developers to publish more details on the distance calculation in the docs. We will notify you when the updates have arrived.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
**Update**

The translation of signal attenuation to distance is not described by an equation, i.e. there is no formula that directly calculates the distance from signal attenuation. Given examples of attentuation-distance pairs (such as 73 dB --> >8m) should be seen as guidance values. The attenuation ranges used by the app's calculation are based on empiric research that - as far as I understand - examined which attenuation intervals would indicate that devices are close enough for the transmission of the virus.

* >73dB is very far away
* 63-73 is far away
* 55-63 is mid-range
* <55 is very close

I hope this answers your question. Since we cannot provide a formula in the docs, I will also close this issue.

----
Corona-Warn-App Open Source Team
