### ISSUE TITLE
What use has the "Enter TAN" box inside the "Have you been tested box"?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#509]
## Your Question

* Documentation File: https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#retrieval-of-lab-results-and-verification-process
* Question: Why is there [this](https://user-images.githubusercontent.com/67682506/104893509-ce2b7e00-5973-11eb-961f-c25e810f7663.jpg) box inside of the app?  

1. Is the only use case for it when user already called the verification hotline and got a TeleTAN to enter it there? 

2. Who issues TANs? Only the hotline or also other bodies?

Edit: Seems like the [health authority can also issue TANs](https://github.com/corona-warn-app/cwa-documentation/blob/8713d0a09e179969e6e94909d18f1f4654966cdf/solution_architecture.md#L87), do they only issue them via phone or via text too? 
Are these also only valid for one hour?

---

## Related Issue

https://github.com/corona-warn-app/cwa-wishlist/issues/331

**Comment by dsarkar** [comment]
The tan box can be found here 
Click Next steps

it is not there if you have scanned a QR code

**Comment by dsarkar** [comment]
![Uploading 297D24FC-323B-4A29-97D7-A1B5C9002E12.png…]()

**Comment by Ein-Tim** [comment]
Thanks @dsarkar but what is the use of this box?
Is this only used if you already called the hotline and want to enter the TAN? Or is it possible to get a TAN without calling the hotline (more specific, is it possible that a lab issues such a TAN which you can enter there)?

**Comment by dsarkar** [comment]
@Ein-Tim, I will forward the question.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The best explanation about this is in [Verification Server - Architecture Overview](https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md)

There is some confusion between the app and the documentation, because when the documentation refers to TeleTAN, this is labelled TAN in the app UI.

From the table [Core Entities](https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md#core-entities) I've extracted two relevant rows:

|Entity|	Definition|	
| ------------- |:-------------:|
|TAN|	Is a proof that the user has a SARS-CoV-2 Test with status positive. Depending on the context the TAN has a different length. Has a default length of 128 Bit.	|
|teleTAN|	Is a subtype of TAN with reduced length and lifetime. This TAN is handed over via phone and contains only uppercase letters and numbers, excluding 0,O and I,1,L. Length of teleTAN is 9 characters, plus 1 check character. The lifetime of a teleTAN is 1h.	|

The role descriptions:
- Hotline User: user with the role “c19hotline”
- Health Authority User: user with the role “c19healthauthority”

are different, but that only seems to make a difference in how their actions are signed. They are both using the Portal Server to generate a teleTAN for the user to input this into the screen labelled "TAN" in the app.

I can only pick this information from the documentation. I can't tell you if the role "Health Authority User" is being actively used at the moment.

**Comment by Ein-Tim** [comment]
Thank you very much @MikeMcC399.

So, this box can be used in two cases:

a) You called the verification hotline and did not click on ["Enter TAN"](https://user-images.githubusercontent.com/67682506/105046168-0b256c80-5a69-11eb-83fb-940703cf04dd.png) field after calling them and waiting for callback but rather dismissed the flow and are now seeing [this](https://user-images.githubusercontent.com/67682506/105046520-7a02c580-5a69-11eb-8c7e-16d7bab534c4.png) screen.
b) You did not call the hotline but received a TAN from the health authority which you can now enter in the "Enter TAN" box.

**Comment by dsarkar** [comment]
@Ein-Tim I got feedback: The only way teleTANs are issued is via the hotline in verbal form.

**Comment by Ein-Tim** [comment]
Okay thanks.
Will close this Issue now.
