### ISSUE TITLE
Question about counting of encounters

### ISSUE THREAD

**Issue by songbird82** [corona-warn-app/cwa-documentation#515]
## Your Question

* Question:  

Hi,  
in my iOS 14.3 „Begegnungmitteilungen“ —> „Begegnungsüberprüfungen“ I find a „1“ for the „übereinstimmende schlüssel“ since 21.1., but my App still says „Keine Risikobegegnungen“. What exactly does this mean for the encounter?
Thanks for the information

**Comment by Ein-Tim** [comment]
Hi @songbird82 👋🏻

This means that the encounter was recorded by the Exposure Notification Framework, the underlying API, provided by Apple, but Corona-Warn-App filtered the encounter out because it was below the threshold (even for Low-Risk encounters).

For more information please see: 
https://github.com/corona-warn-app/cwa-app-ios/issues/1703

**Comment by heinezen** [comment]
Hello @songbird82 ,

encounters recorded by the Exposure Notification Framework that were very short or had a very low signal strength are filtered out by the app and are not taken into account by the risk calculation. The risk of catching Corona from these encounters is almost non-existent, so the app does not include them to reduce te numbers of false-positives.

For your encounter, it probably means that it had one of the following characteristics:

* The distance between you and the infected person was >8 meters
* The encounter was very brief, e.g. you walked by the infected person on the street or you stop you car at a red light and the encounter is with the driver in the car next to yu
* The transmission risk at the time of the encounter was very low. This value estimates how infectious the person was at the time of the encounter. We can calculate it because the time frame between infection and showing symptoms is roughly the same for everyone (e.g. it's 2-5 days for the original Corona strain).  So if your encounter was 14 days ago, but the infected person started showing symptoms only 4 days ago, then it is unlikely that they were already infectious at the time of your encounter

I hope that answers your question. You can read more about the technicall detail in the FAQ entries @Ein-Tim posted above.

Best Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@songbird82 If you are happy with the answer, please close this issue.

**Comment by songbird82** [comment]
Thank you very much for the detailed answers! That clears it up!
