### ISSUE TITLE
Questions about missing doc.

### ISSUE THREAD

**Issue by bionade24** [corona-warn-app/cwa-documentation#518]
Ich arbeite gerade an der GUID-Unterstützung der inoffiziellen CWA für SailfishOS https://github.com/llewelld/harbour-contrac.
 Dabei bin ich auf eine Unklarheiten gestoßen, die mir auch nach mehrfachem Lesen der Dokumentation nicht ersichtlich sind.
 Diese werde ich im Folgenden nun einzeln auflisten:

I'm currently working on GUID support for the unofficial CWA for SailfishOS  > Ich arbeite gerade an der GUID-Unterstützung der inoffiziellen CWA für SailfishOS https://github.com/llewelld/harbour-contrac I found some points that aren't clear from GUID support, that are only guessable throug reverse engeneering. 

> 1. Wie lang ist registrationToken gültig bzw. wie lange lässt er sich einlösen?
1. How long is a registryToken valid or how long can it be submitted?
2. What's the exact difference between REDEEMED and PENDING? Why is REDEEMED necessary when They're INVALID, POSITVE and NEGATIVE?
3. Furthermore: Do I need to store the testresult securely on the device or can I request it multiple times?

Tagging @llewelld

**Comment by MikeMcC399** [comment]
@bionade24 
You might find some of your questions answered in https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf. The document makes several references to the Registration Token.

The link [Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) is posted to the site https://www.coronawarn.app/.

I can't help you more than that though, since I only get my information from the document.

**Comment by MikeMcC399** [comment]
@bionade24 
There is also some information in the documentation [Test Result Server - Architecture Overview](https://github.com/corona-warn-app/cwa-testresult-server/blob/master/docs/architecture-overview.md) which might help you.

**Comment by bionade24** [comment]
@MikeMcC399 Thanks for you help. You first suggestion and the reading the Android Source Code has helped me to be relatively sure in my guesses. Until I don't get anything official, I stay with the things I know now.

**Comment by Ein-Tim** [comment]
This issue was never mirrored to JIRA and the Open-Source-Team did not comment on it. If @bionade24 could comment if he is still interested in the answers to his questions, this would help to make a decision how to proceed with this issue.

**Comment by bionade24** [comment]
I already implemented everything and it works for over a year, so no, I don't have questions anymore. Thx for asking, though.
