### ISSUE TITLE
Update (10 => 5 min) cwa-risk-assessment.md and risk_calculation_enf_v2_overview.pdf

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-documentation#530]
## Where to find the issue

- https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf

-  cwa-risk-assessment.md

## Describe the issue

Says 10 minutes

## Suggested change

should say 5 minuts

**Comment by MikeMcC399** [comment]
Perhaps @tklingbeil can update his diagram to change the 10 minutes to 5 minutes?
[risk_calculation_enf_v2_overview.pdf](https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf)

**Comment by MikeMcC399** [comment]
@dsarkar 

Regarding [cwa-risk-assessment.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md): this document describes risk calculation based on the v1 model. CWA now uses the v2 model, so the document [cwa-risk-assessment.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md) is no longer correct at all. There is an open issue about this point https://github.com/corona-warn-app/cwa-documentation/issues/453.

It is not just a question of changing 10 minutes to 5 minutes in that document. In fact I couldn't see any mention of 10 minutes in that document.

**Comment by MikeMcC399** [comment]
@dsarkar 

This issue has been fixed in the current document https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#mobile-applications.

The document https://github.com/corona-warn-app/cwa-documentation/blob/main/cwa-risk-assessment.md is now deprecated.

You should be able to close your issue now.

**Comment by Ein-Tim** [comment]
@dsarkar Friendly reminder: Please close this issue.

**Comment by MikeMcC399** [comment]
@dsarkar 

- Your issue can be closed since it has been implemented through PR https://github.com/corona-warn-app/cwa-documentation/pull/822 on Jan 25, 2022.

- See https://github.com/corona-warn-app/cwa-documentation/blob/main/images/solution_architecture/risk_calculation.svg linked to from document https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#mobile-applications.
