### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by rhmk** [corona-warn-app/cwa-documentation#54]
## Collaboration?
our friends from Austria are ready with the app: https://github.com/austrianredcross/stopp-corona-android.  Do you know the project, can you share code to speed up development?

**Comment by DevilXTR** [comment]
Problem with the app from the _austrian red cross_ is that it does not use the official Google and Apple Exposure Notifications (e.g. https://www.google.com/covid19/exposurenotifications/ and https://www.apple.com/covid19/contacttracing/). 

This makes the app useless for iOS-user since the app cannot use Bluetooth permanently.

**Comment by rhmk** [comment]
thx

**Comment by tkowark** [comment]
Thanks for pointing us to the project! Besides the limitations mentioned by @DevilXTR, we'll take a look and are happy to learn.

**Comment by abaumg** [comment]
The Austrian app is currently being updated to leverage the Apple/Google framework.
