### ISSUE TITLE
Screenshots for planned versions

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#553]
## Your Question

In the New Features section of CWA 1.14.3 it says:

----

**"Screenshots for the Corona-Warn-App"**

"The website https://www.coronawarn.app now contains all the screenshots for the app, so you can find out about planned features, for example."

----

https://www.coronawarn.app/en/screenshots/ doesn't show any information for planned features, only existing features.

Will that change? Will the page include screenshots for app versions before they are released as well as for the current release?

----
Internal Tracking ID [EXPOSUREAPP-5738](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5738)

**Comment by heinezen** [comment]
@MikeMcC399 Yeah you're right, my mistake. I originally intended to use much more of your original issue text. I've reverted the changes and made a separate issue for the wishlist. The new wishlist item can be found at https://github.com/corona-warn-app/cwa-wishlist/issues/397

> It's also difficult to understand how a bug can become a wishlist item. That is quite confusing.

We usually do this automatically if a contributor accidently describes a missing feature as a bug. However, your issue was an actual bug, so it didn't make much sense to use the approach in this situation.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
Thank you for reverting!

Since this was apparently just a mistake in the release notes, then we can close this issue, since the release notes are tied to the release and don't get re-issued.

My understanding of the process for the screen shots is that they get automatically generated when a release is built, so the process only really covers the current release in any case.

We can follow up any further comments about how we would like information to be shared for future releases in your new corona-warn-app/cwa-wishlist#397 items. I'm expecting this to happen more through blog publications based on past experience.
