### ISSUE TITLE
Norway doesn't have it's own flag in "Transnational Exposure Logging" although it's not part of the EU

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#566]
## Where to find the issue
1. Open the Corona-Warn-App
2. Click on "Exposure Logging Active" or "Exposure logging stopped"
3. Click on "Transnational Exposure Logging" 
4. See that in the top left corner is the flag from the European Union & the one from Switzerland.

## Describe the issue
Norway isn't part of the EU and should therefore be listed like Switzerland, with its own flag.

## Suggested change
Add the flag of Norway near the one from Switzerland.

## Additional information
Difference between Norway & Switzerland: Norway is part of the EEA but not of the EU, while Switzerland is neither part of the EEA nor of the EU. But I don't think that the app is referring to the EEA with the European flag, or?

Hint was given by @Thusid in https://github.com/corona-warn-app/cwa-app-android/pull/2499#issuecomment-789745223.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- The EU interoperability gateway which Norway connects to is run by the EU. Switzerland does not use this gateway.
- The EU lists Norway on [Mobile contact tracing apps in EU Member States](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/travel-during-coronavirus-pandemic/mobile-contact-tracing-apps-eu-member-states_en).

I interpret the flag to refer more to the country / country group running the gateway rather than a political category.

**Comment by thomasaugsten** [comment]
It is also a poltical category because norway is member of the e-health group of the eu and is accepting the guidelines of the e-health group
https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/travel-during-coronavirus-pandemic/how-tracing-and-warning-apps-can-help-during-pandemic_de

**Comment by Ein-Tim** [comment]
Thanks for the answers @MikeMcC399 and @thomasaugsten!
 
Seems like this is not the most obvious implementation (users won't think about the e-health group when they see this flag but rather about the European Union) but is ok for now.

**Comment by MikeMcC399** [comment]
According to [eHealth Network](https://ec.europa.eu/health/ehealth/policy/network_en) "The Network is composed of members coming from all EU Member States and Norway (observer)."
