### ISSUE TITLE
"Exposures with low risk on n day(s)" vs "Exposures on n day(s) with increased risk"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#578]
## Where to find the issue
Inside of the app on the main risk card, see "Steps to reproduce the issue".

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Get an exposure with low risk
3. See that the text for a low risk "Exposures with low risk on n day(s)"
4. Get an exposure with increased risk
5. See that the text for a increased risk exposure is "Exposures on n day(s) with increased risk"

## Describe the issue

The app does not display the number of encounters in the same place for an increased risk encounter (middle of the sentence) as it does for a low risk encounter (end of the sentence).

## Suggested change
Let the app display the number of encounters for both, low and increased risk, in the same place of the sentence (either in the middle or on the end).

So either

"Exposures with low risk on n day(s)" &
"Exposures with increased risk on n day(s)"

or

"Exposures on n day(s) with low risk" &
"Exposures on n day(s) with increased risk"

## Screenshots

See https://www.coronawarn.app/en/screenshots.

---
Internal Tracking ID: [EXPOSUREAPP-6264](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6264)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-6264](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6264)

**Comment by Ein-Tim** [comment]
I provided PR https://github.com/corona-warn-app/cwa-app-ios/pull/4458 addressing this issue.

**Comment by dsarkar** [comment]
Hi @Ein-Tim, suggestion: in order to avoid working on a PR that might be rejected, you can ping me or another Corona-Warn-App Open Source Team member and we will try to get feedback from the dev team.

**Comment by Ein-Tim** [comment]
Hey @dsarkar, yes, I will do that in the future, however, issues should not only be rejected when someone wants to work on it but continuously, so that the issue trackers are kept clean and so that the community knows that open issues are valid and can be worked on / are worked on by the team. Do you agree with me here?

**Comment by dsarkar** [comment]
Hi @Ein-Tim, sure we try to sync as much as possible between the Community and dev team/management/etc... Some issues unfortunately snow under, and only when there is a comment, or in this case a PR,  they "awake again to life". This happens particularly with non-critical issues.

**Comment by mlenkeit** [comment]
@Ein-Tim for what it's worth, let me elaborate on the wording:

* _Exposures with low risk on n day(s)_ describes the _exposures_ as being _low risk_
* _Exposures on n day(s) with increased risk_ describes the _day_ as having an _increased risk_

This makes sense, because the risk calculation (1) first distinguishes between exposures as being either _low risk_ or _increased risk_ and then it aggregates the data by date to decide if the _day_ has a _low risk_ or _increased risk_.

That means there can be a _day with increased risk_, while all exposures on that day were actually _low risk_.

This would overlap with _Exposures on n day(s) with low risk_ and exclude _Exposures with increased risk on n day(s)_.

That's why we have the current wording. Apologies for not explaining this earlier.

1 - [risk_calculation.svg](https://github.com/corona-warn-app/cwa-documentation/blob/main/images/solution_architecture/risk_calculation.svg)

**Comment by Ein-Tim** [comment]
@mlenkeit Thank you very much for the explanation! This makes sense!

> That's why we have the current wording. Apologies for not explaining this earlier.

That's absolutely no problem, I understand that the team has a huge workload and that it is nearly impossible to keep up with everything! Have a relaxed evening & weekend!
