### ISSUE TITLE
.spelling should not use "whitelist" and "blacklist"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#580]
## Where to find the issue
https://github.com/corona-warn-app/cwa-documentation/blob/441b3ed5a5fce093b26dba0bbd1e739742830713/.spelling#L13
https://github.com/corona-warn-app/cwa-documentation/blob/441b3ed5a5fce093b26dba0bbd1e739742830713/.spelling#L122

## Describe the issue
The terms white- and blacklist [should not be used anymore](https://github.com/corona-warn-app/cwa-website/issues/952#issuecomment-791924528).

## Suggested change
Use allow-list and deny-list instead.

## Additional information

I will provide a PR for this.

**Comment by Ein-Tim** [comment]
@dsarkar 

Before I provide a PR, could you clarify internally:

Should we use:

allowlist & blocklist
allowlist & denylist (w/o hyphen)
allow-list & deny-list (with hyphen)

Thank you!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

In the workflow script https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows/checks.yml  
`npm run-script spellcheck`
is commented out.

If you run `npm run-script spellcheck` on a clone of the master branch of the repository by hand, the result is:
>> 206 spelling errors found in 14 files

So my conclusion is that the file https://github.com/corona-warn-app/cwa-documentation/blob/master/.spelling is not being maintained or used in any formal way at this time.

**Comment by Ein-Tim** [comment]
Thank you @MikeMcC399!

Although .spelling is not used in any automatic checks, @mlenkeit recently [referred](https://github.com/corona-warn-app/cwa-documentation/pull/571#issuecomment-811719014) to it.

Also, if there was an internal decision to not use these terms anymore, IHMO they should be updated to not make anyone think that we're still using these terms.

But if the team descides to not change it, it's also ok for me.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Also, if there was an internal decision to not use these terms anymore, IHMO they should be updated to not make anyone think that we're still using these terms.

I don't know if there was an SAP internal decision about it. 

The post you quoted https://github.com/corona-warn-app/cwa-website/issues/952#issuecomment-791924528 doesn't mention it, however one post later https://github.com/corona-warn-app/cwa-website/issues/952#issuecomment-791927211 was from me where I wrote 'The term these days is now "allowlisted"' and I wrote that because Google had changed their [Exposure Notifications implementation guide](https://developers.google.com/android/exposure-notifications/implementation-guide) to refer to [Glossary - Allowlisted accounts](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#gloss_allowlisted).

On a related topic: GitHub is moving to change the default repository branch from `master` to `main` (see https://github.com/github/renaming) for newly created repositories. In fact some of the repositories in the https://github.com/corona-warn-app organisation have been modified too. Unfortunately this broke links in the past and so I would not want to see this [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) repository to be changed similarly at this time.

**Comment by Ein-Tim** [comment]
> The post you quoted corona-warn-app/cwa-website#952 (comment) doesn't mention it,  [...]

I think yes it does, @dsarkar wrote:

> [...] For the RKI survey routers should include in their domains access-list (**apparently we shall not use the word whitelist**):

Also @heinezen commented [here](https://github.com/corona-warn-app/cwa-website/pull/659#pullrequestreview-550094911) (the fact that his statement was unrelated to this PR doesn't mean that what he commented there isn't true, IHMO):

> Correct terminology is "allowlist" (prev known as "whitelist"). no space or separator in beween. Also, use the same word in German, but capitalized ("Allowlist")

I agree with you that we had quite a few broken links because of renaming `master` to `main`, but I don't see where a little change in this file would cause something like this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I stand corrected! Sorry for misreading!

Of course changing the .spelling file will not cause any links to break.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks 👍

But I want to mention that I definitely don't consider this issue here at a high priority (only speaking about me, maybe others do), so if it would be really something that has to be discussed internally please don't let it block the development in any form!

**Comment by Ein-Tim** [comment]
@dsarkar The https://github.com/corona-warn-app/cwa-documentation/labels/in%20review label is applied here since 12.04.2021. Is the review still not finished? If it is finished, what was the result?

**Comment by Ein-Tim** [comment]
This issue became stale. I will close it now.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- See my suggestion in https://github.com/corona-warn-app/cwa-documentation/issues/891 to remove the file [.spelling](https://github.com/corona-warn-app/cwa-documentation/blob/main/.spelling) completely as it has not been actively used in the last two years.
