### ISSUE TITLE
Bluetooth multiple connections at the same time

### ISSUE THREAD

**Issue by pepintos** [corona-warn-app/cwa-documentation#594]
How can device's bluetooth connect to more than other other bluetooth? Does the app have multiple bluetooth objects?

**Comment by Ein-Tim** [comment]
@pepintos 

The Bluetooth part (e.g. sending & receiving of RPIs) is done by the Exposure Notification Framework/System from Apple/Google. 

The documentation from them can be found here: 

https://developer.apple.com/exposure-notification/

https://developers.google.com/android/exposure-notifications/exposure-notifications-api?hl=de

Since this API is integrated into the OS (for Apple) and into the Google Play Services (for Google), the restriction that only one device can be connected does not apply here. 

BTW, I can easily connect multiple Bluetooth devices to my iPhone, is this not possible under Android?

**Comment by MikeMcC399** [comment]
The Exposure Notification Bluetooth specification is on https://www.blog.google/documents/70/Exposure_Notification_-_Bluetooth_Specification_v1.2.2.pdf

**Comment by Ein-Tim** [comment]
I suggest to close this issue now (cc @dsarkar)

**Comment by dsarkar** [comment]
Hi @pepintos,

 Thanks for contributing. We understand that your question has been answered by @MikeMcC399 and @Ein-Tim. We will close this issue now. Don't hesitate re-opening, or creating a new issue if you have more questions. Best wishes, DS 

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Regarding connections, the specification says:
"During the Bluetooth broadcast, advertisements are to be **non-connectable** undirected of type ADV_NONCONN_IND (Section 2.3.1.3 of 5.2 Core Spec)."
