### ISSUE TITLE
Would it be feasible to add a location type for public transportation to the event tracking functionality?

### ISSUE THREAD

**Issue by byteborg** [corona-warn-app/cwa-documentation#596]
## Your Question
In file https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md#qr-code-structure `enum TraceLocationType` specifies several types of possible locations. Those are all static (in the sense of non-moving, bound to a specific geographic location).

Wouldn't it be feasible to add location types for moving location entities as well, such as trains, planes and automobiles?

**Comment by fynngodau** [comment]
I support this proposal – vehicles like busses are a perfect fit for the CWA, as there is not much space and they frequently aren't air conditioned. Therefore, the use of the CWA events feature in public transport should explicitly be promoted.

**Comment by heinezen** [comment]
@byteborg 

Since there is no technical limitation, I guess it would be possible. If you are interested in this feature, please open an issue in the https://github.com/corona-warn-app/cwa-wishlist/ repo. We will then track and discuss it internally :)

----
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
@heinezen Maybe this issue could be moved there?

**Comment by heinezen** [comment]
@fynngodau I would have to rephrase the initial post to sound like a feature request and we know some users don't like if we take too much control over their posts. That's why we rather like to encourage everyone to make a new wishlist issue in this case.

@byteborg I see that you made https://github.com/corona-warn-app/cwa-wishlist/issues/496 , so we will close here and continue any further discussion in the new issue :)

----
Corona-Warn-App Open Source Team
