### ISSUE TITLE
I cannot see my positive test result in the app after turning on exposure logging again

### ISSUE THREAD

**Issue by farhadnowzari** [corona-warn-app/cwa-documentation#598]
Hi,
I wanna know how can I see my positive result again.
I scanned the qr code and I was positive then entered the symptoms and allowed sharing but then there was an option to turn on the exposure logging again and now the result is gone and I cannot scan it again.

**Comment by DerVogel2020** [comment]
So you saw the result and shared it?
Why do you want to see it again? I think it's the design: You log again you potential exposures and can share them again if you get tested the next time.

**Comment by Ein-Tim** [comment]
@farhadnowzari 

Are you using an Android or an iOS Device? 

So you saw [this](https://www.coronawarn.app/assets/img/screenshots/de/ios/iPhone%2011%20Pro-homescreenrisk_show_positive_test_result_0001.png) screen, clicked on "Andere Warnen", followed the instructions on the screen. 
After the sharing process, you clicked on "Risiko-Überprüfung einschalten" (as shown [here](https://user-images.githubusercontent.com/1157991/107514251-b7aac800-6ba9-11eb-99e8-f070a3f4b17d.PNG))? 

If you've done this, you should have seen the warning which says that your current test result will be removed from the app if you continue ([link](https://github.com/corona-warn-app/cwa-app-ios/pull/1959/files#diff-130eb13421036eb3058649fa7623c37dcdf42a3ed0069060bfe0f81a95403f6fR1005) to iOS strings).

So, conclusion, if you've done what I've described above you're not able to see this test result inside of the app again.

**Comment by farhadnowzari** [comment]
Ah ok. 
I haven't exactly read the messages sorry but I did the same steps as you described. But it could be helpful if I could see the results still just to see a log.

And do u know  how does the contacting happen?
It said someone will contact me. Do you know how long does it take?

**Comment by MikeMcC399** [comment]
@farhadnowzari 

It sounds like you are still infected, so you should still be isolating and there should be no need to activate exposure logging yet, because that is only for when you think that you are not infectious or you do not know if you are infectious.

For later, when you have recovered from an infection then the FAQ advice is on https://www.coronawarn.app/en/faq/#recovered.

As the previous comments said, you only scan your test once and share the results once, then at first exposure logging should be disabled.

If you want to contact your local health authority, you can use the tool https://tools.rki.de/PLZTool/en-GB to find their contact information. This information is listed in the FAQ https://www.coronawarn.app/en/faq/#who_can_help.

**Comment by Ein-Tim** [comment]
@farhadnowzari 

I think that sounds good! If you don't need our help here anymore, feel free to close this issue.

Get well soon!

**Comment by farhadnowzari** [comment]
Sure. 
Thanks again
