### ISSUE TITLE
Publish repository for s.coronawarn.app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#603]
## Where to find the issue
Users that scan a QR-Code or click on a link from a RAT are redirected to the app through the page s.coronawarn.app. This page is, in contradiction to e.coronawarn.app, is not open source. 

## Describe the issue & Suggested change
The page shows "Download the Corona-Warn-App to check in." but for quick tests it would have to be "Download the Corona-Warn-App to register your rapid antigen test.".

**Comment by thomasaugsten** [comment]
Its the same to https://github.com/corona-warn-app/cwa-event-landingpage/

**Comment by Ein-Tim** [comment]
Yeah and that's the problem, because s.coronwarn.app says "Download the Corona-Warn-App to check in." but for quick tests it has to be something else, for example "Download the Corona-Warn-App to register your rapid antigen test.".

**Comment by MikeMcC399** [comment]
@Ein-Tim 
On Android 8 with Google Chrome as the default browser, when I attempted to open https://s.coronawarn.app it only briefly showed me that page before immediately forwarding the browser to the Google Play Store. It did not even display https://s.coronawarn.app long enough for me to read the contents. The same happens if I access https://e.coronawarn.app from Android.

If I open either of the sites https://s.coronawarn.app or https://e.coronawarn.app in Google Chrome from a Windows machine, then I see the text "Download the Corona-Warn-App to check in."

Perhaps you should add an issue to https://github.com/corona-warn-app/cwa-event-landingpage/ to change the text to cover both check in and rapid antigen tests?

You could also open an issue to modify the https://github.com/corona-warn-app/cwa-event-landingpage/#readme on that site to say that it is being used for https://s.coronawarn.app as well as for https://e.coronawarn.app. Only the use for Event landing is documented.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thanks, I'll do that! I can confirm that this is only opened briefly, but imagine a situation where the user get's the link to the Corona-Warn-App via Mail and opens the link from the Mail on a PC and then sees this text. I think there will be some users that will be confused then, because they didn't want to check-in somewhere...

Closing this here and will follow up soon in https://github.com/corona-warn-app/cwa-event-landingpage/
