### ISSUE TITLE
Why is the CWA able to scan vaccination certificates without valid signature?

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-documentation#634]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) - I don't know, someone should check on iOS
* [x] Bug is not already reported in another issue

## Technical details

- Device name: LG-G4 (LGH-815)
- Android version: 6.0
- App version: 2.3.2

## Describe the bug

CWA is now able to store DCC vaccination certificates - that's great, and thanks to everyone involved for accomplishing that work! ❤️ 

As I don't own my personal DCC bar code yet, I tried out to scan an example code found on
https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/examples which uses this bar code:
https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/examples/01_example.png 

This bar code was added flawlessly to CWA, but it was not possible to add it to CovPass app or to verify it successfully with CovPassCheck app.

**CWA's representation of example DCC vacc cert scanned from GH source:**
<img src="https://user-images.githubusercontent.com/68376758/121529432-af01bb80-c9fc-11eb-98bf-159c77f82c30.png" width="300" >

**CovPass app's error dialog when scanning example DCC vacc cert scanned from same GH source:**
<img src="https://user-images.githubusercontent.com/68376758/121531775-06089000-c9ff-11eb-9f1a-c13de0aca468.png" width="300" >

**CovPassCheck app's error dialog when scanning example DCC vacc cert scanned from same GH source:**
<img src="https://user-images.githubusercontent.com/68376758/121532088-5253d000-c9ff-11eb-93a0-a429c15e79e2.png" width="300" >

It's obvious, that the example QR code does not have a valid signature issued by an authorized health authority.
While CWA checks the json payload of the DCC for validity afaik, it does not check its signature.

## Steps to reproduce the issue

1. Scan QR code from https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/examples with CWA 
2. Scan QR code from https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/examples with CovPass app 
3. Scan QR code from https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/examples with CovPassCheck app 
4. See differences

## Expected behaviour

I would have expected CWA to refuse a DCC that does not contain a valid signature issued by an authorized health authority.
For me it's not clear, if this behaviour is intended, or maybe a bug, or maybe there is already a validation algorithm planned for a future release?

## Possible Fix

I would propose to add a signature check in a future release of CWA to prevent
* occasionally distracted people (like me) to scan the wrong QR code out of their desk's paper mountain, especially when being stressed while preparing for a holiday, and then later experiencing a bad surprise at border control ;)
* users to being able to abuse sample codes when they're used as gate passes in other situations: **theoretically**, the gate keeper **should always see** another personal document (like id etc.) to validate the presented code against the holder. **Practically, this won't  likely be the case in many situations** for future events (like entrance to cinema, stadium, restaurants etc...). While people still may scan other peoples' valid DCCs, it's at least increasing the level for abuse compared to scanning arbitrary codes found in internet into CWA.

I don't know if it might be a good idea to add an explanation to the FAQ about the current issue. 

Cheers, v.

---
Related to topic: Check signature of certificates
Internal Tracking ID: [EXPOSUREAPP-8010](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8010) Android
Internal Tracking ID: [EXPOSUREAPP-8330](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8330) iOS

**Comment by heinezen** [comment]
@vaubaehn 

We can leave it open for visibility.

I've moved it to cwa-documentation and changed the title to a question. Maybe we can make an FAQ entry with the info, but I don't know if that's necessary.

----
Corona-Warn-App Open Source Team

**Comment by AnTu2702** [comment]
I was also able to create own qr-codes that were successfully imported to cwa app resulting in a blue colored vaccination box.
I can understand your argument, but:
1. CovPassApp IS validating the COSE‘s Signature - and people expect identical behaviour for acceptance if your app
2. As a user of your app I would like to know wether my vaccination cert is invalid BEFORE the gatekeeper tells me!

**Comment by MikeMcC399** [comment]
@AnTu2702
> I was also able to create own qr-codes that were successfully imported to cwa app resulting in a blue colored vaccination box.

Did you by any chance try out the [CovPassCheck-App](https://digitaler-impfnachweis-app.de/impfschutz-pruefen/)?

**Comment by vaubaehn** [comment]
@AnTu2702 
In general I'm agreeing, but
>     2\. As a user of your app I would like to know wether my vaccination cert is invalid BEFORE the gatekeeper tells me!

There are two types of invalidity: either the issuer's signature key is/became invalid (afaik some kind of expiration was considered), or the health certificate itself expired (i.e., the vaccination/test/immunity "expired"). For the latter, I hope CWA is validating the json payload against expiration while scanning... did you try that out also?

And that the issuer's key expires will usually be after the health certificate expired, so I guess that won't be a critical point.

**Comment by thomasaugsten** [comment]
The CWA handles DCCs as a wallet app only in compliance with the EU guidelines, this means no validation.
Validation is done only by the verifier app.
There is at the moment no assumptions that issuer will issue DCCs with an invalid signature to german citizens and a valid signature at scan time will not ensure a valid signature after scanning.

Also is the signature only a small part what the verifier has to verify. The more important part are the acceptance rules of each country to enter the country at a specific date. We will add a functionality to pre check the acceptance rules of each country in advance for a specific date. This means every country has a different interpretation what is the expiration date of a certificate.

**Comment by thomasaugsten** [comment]
There will be a rules available at the EU DCC Gateway. This rules will be applied on the user device locally when the enters specific parameter like county and date.
More information:
https://github.com/ehn-dcc-development/dgc-business-rules

**Comment by vaubaehn** [comment]
@thomasaugsten Thank you!

**Comment by treysis** [comment]
> There will be a rules available at the EU DCC Gateway. This rules will be applied on the user device locally when the enters specific parameter like county and date.
> More information:
> https://github.com/ehn-dcc-development/dgc-business-rules

Would be great if that was available also as a list for better overview, not having to query every single country for an extended trip. E.g. show a list with all countries, next column with current status or from what date travel will be allowed/denied.

**Comment by MikeMcC399** [comment]
@treysis 

> > There will be a rules available at the EU DCC Gateway. This rules will be applied on the user device locally when the enters specific parameter like county and date.
> > More information:
> > https://github.com/ehn-dcc-development/dgc-business-rules
> 
> Would be great if that was available also as a list for better overview, not having to query every single country for an extended trip. E.g. show a list with all countries, next column with current status or from what date travel will be allowed/denied.

It would probably be better to continue this discussion as a separate topic on https://github.com/corona-warn-app/cwa-wishlist since the topic about rules doesn't fit the title of the original subject "Why is the CWA able to scan vaccination certificates without valid signature?" here in https://github.com/corona-warn-app/cwa-documentation/issues/634 and you are asking for new functionality.

**Comment by Ein-Tim** [comment]
> There will be a rules available at the EU DCC Gateway. This rules will be applied on the user device locally when the enters specific parameter like county and date.

Work on this on the CWA-Server: https://github.com/corona-warn-app/cwa-server/pull/1446

**Comment by thomasaugsten** [comment]
You will find this list on https://reopen.europa.eu/de

**Comment by treysis** [comment]
Yeah, it would be great to have this as a table, not having to query every country manually and do manual calculation.

**Comment by llouc** [comment]
no matter what "EU guidelines" we have,
CWA and CovPass/Check have different concepts and this can lead to different PASS/FAIL for exactly the same QR-code.

the reason(s) for this difference is irrelevant. it happens "in the field" right now.

both concepts should merge/share QR-math/sourcecode.
if this is not possible asap, CWA needs to remove its QR function. with a link to CovPass/Check.

so, instead of having several apps, "trying to do" multiple tasks, it should be one app only, making "one" perfect job.

if "too many criteria" is the problem, then a binary "pass/fail" is not the solution. (but maybe a table).
simplicity (for the user) is not (always) the right answer.

coding and development is not the problem. but bad concepts are often just setup by "bad architects" (or management).

easy statements for me. I know ;)
forgive me for posting "opinions", maybe even in the wrong place

**Comment by thomasaugsten** [comment]
Can you please elaborate where exactly is the issue to scan an invalid or expired certificate except it is different. 
You cannot prevent the user to show a screenshot or website which looks like the app.

**Comment by llouc** [comment]
I understand your argument.
Imagine somebody providing "illegal" QR-codes to a CWA user (no tech skills). Maybe even for money.

"gate-keeping" is still secure. (e.g. CovPass/Check)
but CWA becomes the "fav target" for bad guys.

no "use case"? wired idea?

**Comment by treysis** [comment]
Illegal QR-Codes? If you scan them with CovPassCheck, they will still turn out as invalid. I don't see your point.

**Comment by llouc** [comment]
please read my 1st statement again. CWA could be a vulnerable target. this could harm your reputation.

I can cross-check with 3 apps.
normal users will not.

they will be happy having a PASS in CWA.
then they will e.g. travel ... and meet a gate-keeper using more/different/updated criteria = FAIL.

both apps pretend to conduct the same task (QR-code validation).
but with different critera = potential conflict.

I still dont know if this scenario is possible. But I guess it is. due to e.g. the missing signature check of CWA.

**Comment by My1** [comment]
I agree I would say that some kinda cert check should be done if possible. if the device is very old the app could tell the user that it loaded the cert but could not verify it.

**Comment by Ein-Tim** [comment]
I'm sorry to say this but the press writes that this is a "schwerwiegende Sicherheitslücke" (https://www.br.de/nachrichten/wirtschaft/impf-zertifikat-in-der-corona-warn-app-maengel).
I recommend to add signature checks, not only to prevent bad press but also to catch up with nearly all other EU wallet apps, which are verifying the signature. 

I know, if everybody would use the CovPassCheck App and look at the id card this wouldn't be necessary and I also know that this has to be done according to the guidelines, but it makes no sense to say that the guidelines are like this if nobody else cares about the guidelines.
Yes for sure you could argue that the people should follow the guidelines but they just don't and they won't because they're lazy or just think that it's enough to take a look at the certificate. 
Try to explain somebody who's responsible for the guest registration and that the guests are tested, vaccinated or recovered what a signature is and explain that he/she has to check every QR code with an extra app and also has to see the ID document. 
Everybody will say that this is not practical. 

So we should really adopt to the reality here and add signature checks here. 

Have a good night.

**Comment by treysis** [comment]
The article is basically bullshit. The only problem is that nobody anticipated that the general public has no idea about IT (and even less about encryption), and that press will jump anything in regard to these apps.

Imagine this scenario: you add a signature check. Somebody will then write an article that you can just fool the bouncers by showing a manipulated screenshot and how insecure the whole system is.

I don't know if that would result in _less_ bad press, or just _different_ bad press. So, if there is a lot of "bad press" it might rather raise awareness for the requirement of using CovPassCheck (or whatever the other countries use) and ID checks.

In the end, too much is just clickbait articles and there's little to do against it. Basically, the whole system is useless on a national level because proper checks are too rare.

**Comment by Ein-Tim** [comment]
@treysis 

> The article is basically bullshit.

Yes, I know. But the people reading this (my father sent me this article) think that it's true and that the security is really bad. 

> Somebody will then write an article that you can just fool the bouncers by showing a manipulated screenshot and how insecure the whole system is.

I assume this would result in another bad press, but somehow this is obvious and shouldn't be a scandal. 

Your last idea is a good one, feel free to open a new wishlist issue for this! 

But another valid point (which was raised here already) which speaks for signature checks is that if I get a QR-Code from a pharmacy, I scan it with the CWA and then travel to Spain (for example). They ask me for the QR-Code and I show it, they scan it and then they say that the QR-Code is not valid. I assume that their scanner app has the same general error message like CovPassCheck, which doesn't really tell one reason why this particular QR-Code is invalid. 
Now I'm at the border in Spain, didn't took my yellow booklet with my because I thought yeahy we're going digital. 
I do some investigation (phone the pharmacy) and then  it becomes clear that the QR-Codes were somehow issued with a signature that's not valid. Why didn't CWA tell me when importing the QR-Code? In the worst case the user will directly uninstall the app because of this.

**Comment by llouc** [comment]
> Imagine this scenario: you add a signature check. Somebody will then write an article that you can just fool the bouncers by showing a manipulated screenshot and how insecure the whole system is.

this is not true. as many understand already: the SCANNING is the point. NOT just "showing".

if you SHOW a fake QR, CWA could SCAN and yield GREEN, CovPass/Check will scan and yield RED.
if you SHOW a correct QR, CovPass/Check will scan + yield GREEN.
all this is independent from "show-by-app", "screenshot" or "paper".

this is the baseline of the security for QR codes. the code is the KEY, the scanning (criteria eval) is the LOCK.
**I will not open my door if you just show me a key. it needs to FIT**. (metaphor for kids)
get used to it!

repeatedly saying, that CovPass/Check will yield correct status, is just a bad excuse for keeping a bad concept in CWA.

a concept bug is always more severe as a development bug. if this is due to EU-guidelines, then they have a concept bug IN the guidelines. and CWA copied that.

the term "wallet app" implies that the key(QR-code) is JUST stored.
but surprise.... the "wallet app" also shows the STATUS. so it NEEDS a valid unLOCK function. (= ALL criteria checks)

so if you really want to have the wallet-function only - REMOVE the status GREEN/RED at least.

the PRESS is just like a HACKER. they will exploit every weakness. even with "bullshit statements".
but no matter how stupid a statement is, somebody will RECHECK in depth. nothing will vanish over time.

tick tock...

BTW: 
Ein-Tim is right. "zero-info-in-case-of-failing" is another problem. see covpass-android-issue-18

**Comment by dsarkar** [comment]
Dear community!

This topic and implications are discussed internally and hopefully we can give you more information here soon.  

Best,

---
Corona-Warn-App Open Source Team

Related to topic: Check signature of certificates
Internal Tracking ID: EXPOSUREAPP-8010

**Comment by treysis** [comment]
> this is not true. as many understand already: the SCANNING is the point. NOT just "showing".

Yes, I never stated that scanning isn't the point. I am saying that if the app shows the status, bouncers (or whoever) will assume more and more often that this is already sufficient proof ("because the app said so...") and that checking with the CovPassCheck app is optional. If the app wouldn't display the status, bouncers would maybe learn better that "hey, this is just a QR code, what does it actually mean? I need to check with CovPassCheck" instead of just accepting what might actually just be a manipulated pic.

**Comment by llouc** [comment]
> 
> 
> > this is not true. as many understand already: the SCANNING is the point. NOT just "showing".
> 
> ... If the app wouldn't display the status, bouncers would maybe learn better that "hey, this is just a QR code, what does it actually mean? I need to check with CovPassCheck" instead of just accepting what might actually just be a manipulated pic.

its **not** a "maybe". they are forced to scan with e.g. CovPassCheck.
security by concept/design.
my "wallet" is black and with. no green or red lights.

**Comment by heinezen** [comment]
> I'm sorry to say this but the press writes that this is a "schwerwiegende Sicherheitslücke" (https://www.br.de/nachrichten/wirtschaft/impf-zertifikat-in-der-corona-warn-app-maengel).

The article is based on a profound and dangerous misunderstanding of the way certificates have to be validated. Vaccination certificates must always be verified on a trusted third party device (e.g. by using the CovPassCheck app). **Viewing the QR code display in the CWA is not a verification.** User devices cannot be trusted as they can contain a manipulated version of the app or show a forgery of the CWA display via screenshot. The CWA basically cannot prevent manipulation on the user's device, therefore an external check is always necessary.

> Yes for sure you could argue that the people should follow the guidelines but they just don't and they won't because they're lazy or just think that it's enough to take a look at the certificate.
> Try to explain somebody who's responsible for the guest registration and that the guests are tested, vaccinated or recovered what a signature is and explain that he/she has to check every QR code with an extra app and also has to see the ID document.
> Everybody will say that this is not practical.

Without following the guidelines (i.e. using CovPassCheck on a trusted third-party device), the certificate verification is not secure (regardless of whether it is practical or not), even if CWA checks the signature. People need to understand this sooner rather than later. Digital signatures do not create trust by existing. Security requires that specific protocols are followed to be effective.

Introducing measures that check the signature inside the CWA would only "fix" the perception of security rather than be an actual security measure; they would essentially be security theater. Implementing such a thin is a double-edged sword because it may lead people to believe that the wrong verification process is now safe. In the end, this might compromise security even more.

----
Corona-Warn-App Open Source Team

**Comment by My1** [comment]
> Viewing the QR code display in the CWA is not a verification

while true actually verifying in app also helps users to see that their cert actually is valid, which was a point noted multiple times.

**Comment by heinezen** [comment]
@My1 

> while true actually verifying in app also helps users to see that their cert actually is valid, which was a point noted multiple times.

This is correct and a valid consideration. I wanted to stress that this would purely be a convenience feature and should not be seen as a security measure.

----
Corona-Warn-App Open Source Team

**Comment by treysis** [comment]
> This is correct and a valid consideration. I wanted to stress that this would purely be a convenience feature and should not be seen as a security measure.

Therefor the additional information should only be shown on the "Certificate" overview screen, not when displaying the QR code. Display of the QR code should ideally only contain the code. No name, no DOB, no DOV, no current vac status. This should make it even more clear that evaluation has to be done on a separate external device.

**Comment by Ein-Tim** [comment]
> The article is based on a profound and dangerous misunderstanding of the way certificates have to be validated. Vaccination certificates must always be verified on a trusted third party device (e.g. by using the CovPassCheck app). Viewing the QR code display in the CWA is not a verification. User devices cannot be trusted as they can contain a manipulated version of the app or show a forgery of the CWA display via screenshot. The CWA basically cannot prevent manipulation on the user's device, therefore an external check is always necessary.

I know, you know, the community here knows. 8 out of 10 (according to another article) restaurants in Munich don't know 🤷🏻‍♂️ It makes not sense to just argue something that is not done. In the end the user decides how a product is used, and not some PDF documents somewhere in the internet.

> Introducing measures that check the signature inside the CWA would only "fix" the perception of security rather than be an actual security measure; they would essentially be security theater. Implementing such a thin is a double-edged sword because it may lead people to believe that the wrong verification process is now safe. In the end, this might compromise security even more.

I see your point here, but at least it wouldn't be possible anymore to just scan any certificate without a valid signature into CWA so the gatekeepers can't be fooled with this anymore. 

But I'll now just leave this over to you, if there was the internal decision not to implement signature checks, that's fine for me too. You know what you do (I don't mean this ironically!)

Thank you @heinezen!

**Comment by heinezen** [comment]
> It makes not sense to just argue something that is not done. In the end the user decides how a product is used, and not some PDF documents somewhere in the internet.

Unfortunately, this is some of the rare cases where the user behaviour needs fixing. Cryptography is not magic, it is a tool that needs to be used properly. That does not mean that the user is to blame, btw. However, if the users do not follow the correct process, the process will not be secure. I have checked if RKI may have some official communication about this, but I currently don't know how that would look like. Right now, we only respond to the discussion on Github.

----
Corona-Warn-App Open Source Team

**Comment by My1** [comment]
> This is correct and a valid consideration. I wanted to stress that this would purely be a convenience feature and should not be seen as a security measure.

sure, I have no problem with that.



> Therefor the additional information should only be shown on the "Certificate" overview screen, not when displaying the QR code. Display of the QR code should ideally only contain the code. No name, no DOB, no DOV, no current vac status. This should make it even more clear that evaluation has to be done on a separate external device.

totally agree. aside from maybe a heading like it being the corona app or whatever to just immediately see that you actually are on a corona qr rather than a contextless qr, it shouldnt show much extra stuff except maybe an on screen hint to have it scanned by the covpasscheck and having your ID card verified.

**Comment by llouc** [comment]
CWA is able to scan and store fake QR codes = severe design/concept flaw.

did "you" forget already ?

blaming the user will lead to a specific impression in public = failure and arrogance

saying "I dont blame the user, but he did sth wrong" 
= is even more arrogant because its a illegal statement on logic level

no matter how many "nice statements or explainations" in-app or outside-app there will be

**Comment by thomasaugsten** [comment]
If the CWA check the signature it will not prevent to show fake qr codes.  It will encourage that is enough to scan this in an app and not check with CovPass Check. 
But it is also planned to add signature and expiration check in the CWA. But again this will not add any security or helps to prevent fake qr-codes

**Comment by My1** [comment]
@thomasaugsten while true we need to consider both sides and a user should be able to know whether his qr is valid so verifying it isnt something we should just leave out. but as others said the qr screen obviously shouldnt show much about validity and stuff for obvious reasons.

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-app-android/pull/3664 will add a hint that the CWA doesn't check whether the certificates are valid or not.

**Comment by unpairedliabilitylibrarian** [comment]
> 
> 
> If the CWA check the signature it will not prevent to show fake qr codes. It will encourage that is enough to scan this in an app and not check with CovPass Check.
> But it is also planned to add signature and expiration check in the CWA. But again this will not add any security or helps to prevent fake qr-codes

A signature verification check by the CWA would not increase security. But as someone who wants to check if the printed document with the QR-Code has been successfully signed by the RKI, this would be useful. 

That is, because the CovPassCheck-App either says "proof of vaccination valid" or "proof of vaccination not valid". So you have to wait 14 days until you have full protection by vaccination before you can verify if the originally printed QR-Code has a correct signature. A wrong signature or just not signed QR-Code would not be detected in the moment you receive it. Maybe there are scammers who sell those QR-Codes and someone who bought it believes that he has to wait 14 days or there was a technical failure in the process of signing by the legitimate pharmacy / vaccination centre / medical.

**Comment by skyerjoe** [comment]
Device: mi9tpro
CPC Version: 1.28.4 
Related to: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/18

2 Certs EU Vaccinations printed from Pharmacy :

Check with CPC: 

-2/2 : Not Valid 
-1/1 Recovered: Not Valid 

best regards

**Comment by MikeMcC399** [comment]
@skyerjoe 
> 2 Certs EU Vaccinations Certifiacte printed from Pharmacy :
> 
> Check with CPC:
> 
> -2/2 : Not Valid
> -1/1 Recovered: Not Valid

Was the vaccination date more than 14 days ago?
If yes, did you try again with CovPassCheck-App?
There were reports that the CovPass backend was having problems and incorrectly rejecting valid certificates. This is supposed to be resolved now.

What does the Corona-Warn-App say about these certificates?
Are the vaccination certificates shown as complete?

**Comment by skyerjoe** [comment]
@MikeMcC399 

Hello Mike 

I dont have the cwa i have the cctg and these are working in the app.

Yeah may it due the 14 days duration time cause my cert was issued with an wrong date, today i was at the pharamacy again got a new cert with right date and now the cert is valid. 

But if cpc cannot difference between techincal problems and duration time it's really weird and confusing. 

Thanks for helping me 

Ps: i've delete my thread is there any possibilty to recover it ?

**Comment by My1** [comment]
> But if cpc cannot difference between technical problems and duration time it's really weird and confusing.


totally agree.
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/21

**Comment by Ein-Tim** [comment]
Seems like Version 2.7 will add signature checks: https://github.com/corona-warn-app/cwa-app-ios/pull/3194

**Comment by Ein-Tim** [comment]
Is it to early to apply the `Fix 2.7` label here?

**Comment by Ein-Tim** [comment]
Signature checks were implemented in today released version 2.7. I can confirm that they are working.

**Comment by vaubaehn** [comment]
As I'm currently debugging business rules with self created certificates, would be nice _not_ to have DCC validation... But I could open a wishlist issue for this.

🏃 💨 

😉

**Comment by vaubaehn** [comment]
I think I will close this issue now, as I have the right button for it.
Cheers, and thanks for discussion and implementation!

**Comment by markil01** [comment]
With this latest release 2.7.1 it seems that ALL previously valid UK vaccination certificates have now become invalid.
My certificate comes from the NHS and I was able to import and validate it successfully in the previous version.
It is now invalid.

This topic is now causing some waves in the UK for anfew million EU citizens.

**Comment by vaubaehn** [comment]
@markil01
Could you please provide some more details about what error/message you see where by providing a screenshot/stacktrace/description.
Thanks in advance

**Comment by dsarkar** [comment]
@markil01 Thanks for reporting. I will cross-check internally, if the following "theory" is correct: If you were able to import UK certificates, apparently the UK NHS used the same scheme/format as the EU does. However, there is no digital signature (or a different format, or not distributed amongst the EU) that these are valid documents. See the map and the table here: https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en#how-can-citizens-get-the-certificate
Apparently the UK is not participating. However, I will come back to you and confirm the "theory".

**Comment by Ein-Tim** [comment]
AFAIK you were able to import the UK certificates but they were never valid. So if you could try to scan the QR-Code you received from the NHS with the CovPassCheck-App, I think it will say that the certificate is not valid.

**Comment by markil01** [comment]
> AFAIK you were able to import the UK certificates but they were never valid. So if you @markil01 could try to scan the QR-Code you received from the NHS with the CovPassCheck-App, I think it will say that the certificate is not valid.

Not entirely correct. 
I was successful in importing the UK certificate into the Corona Warn App and having it validated until last week. Since 2.7.1., that previously uploaded certificate is now reporting the error of an invalid signature.
A re-upload of an updated
![Screenshot_20210819-072048_Corona-Warn](https://user-images.githubusercontent.com/89182718/130051162-47fda770-0b03-4a21-b619-2bdb5883bd71.jpg)
 QR code is not resulting into that problem straight away.

**Comment by markil01** [comment]
> @markil01 Thanks for reporting. I will cross-check internally, if the following "theory" is correct: If you were able to import UK certificates, apparently the UK NHS used the same scheme/format as the EU does. However, there is no digital signature (or a different format, or not distributed amongst the EU) that these are valid documents. See the map and the table here: https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en#how-can-citizens-get-the-certificate
> Apparently the UK is not participating. However, I will come back to you and confirm the "theory".
> 
> Corona-Warn-App Open Source Team

Correct.
It seems the NHS does not include a valid signature into their QR codes.

**Comment by markil01** [comment]
> AFAIK you were able to import the UK certificates but they were never valid. So if you @markil01 could try to scan the QR-Code you received from the NHS with the CovPassCheck-App, I think it will say that the certificate is not valid.

Since 2.7.1 that is indeed the behaviour.  Even a previously (before 2.7.1)  uploaded certificate which had been marked as valid became now invalid, without a new upload.

**Comment by Ein-Tim** [comment]
@markil01 

Do you still have access to the QR code you received from the NHS? 
If yes, please [download the CovPassCheck-App](https://play.google.com/store/apps/details?id=de.rki.covpass.checkapp) and scan the QR code with it and tell us the result! 
Thank you!

**Comment by markil01** [comment]
> @markil01
> 
> Do you still have access to the QR code you received from the NHS?
> If yes, please [download the CovPassCheck-App](https://play.google.com/store/apps/details?id=de.rki.covpass.checkapp) and scan the QR code with it and tell us the result!
> Thank you!

Unfortunately,  due to country restrictions I am not able to download the above app. But I tested the same QR code with the Swiss version of the QR code check with the same result. Seems they also already included the digital signature check.

![20210819_112141](https://user-images.githubusercontent.com/89182718/130054151-0087fc2f-4e16-4357-9b0c-de9d336c63f1.jpg)

**Comment by Ein-Tim** [comment]
@markil01 

Okay, and here you see, you were able to import the certificate into the Corona-Warn-App but it was never really valid.

**Comment by My1** [comment]
at least the swiss app actually tells you this compared to the CovPassCheck which tells you practically nothing

**Comment by vaubaehn** [comment]
@markil01 
You wrote above
> A re-upload of an updated QR code is not resulting into that problem straight away.

What exactly do you mean? I'm getting it like, from some point in time on NHS issued certificates that contain valid digital signatures, and these can be imported into Corona-Warn-App without any problems. Did I understand it correct?

**Comment by MikeMcC399** [comment]
According to @thomasaugsten the status of the UK NHS vaccination certificates in the EU environment was still not finalised. Maybe he could let us know the latest official status?

See also https://github.com/corona-warn-app/cwa-wishlist/issues/567#issuecomment-871663665

**Comment by dsarkar** [comment]
@MikeMcC399 @markil01 I just raised this topic internally: There are negotiations to include the UK NHS vaccination certificates (with their signature) in the EU environment, but at this stage we still don't know when it will be implemented (we assume that it will happen).

**Comment by markil01** [comment]
> @markil01
> You wrote above
> 
> > A re-upload of an updated QR code is not resulting into that problem straight away.
> 
> What exactly do you mean? I'm getting it like, from some point in time on NHS issued certificates that contain valid digital signatures, and these can be imported into Corona-Warn-App (including v2.7.1 with digital signature check) without any problems. Did I understand it correct?

No, I uploaded the NHS certificate before the 2.7.1 release. It seem the previous version did not check for a valid signature.  I don't know if the certificate included a valid signature in July (when I uploaded my certificate for the first time). But now it does not.

**Comment by vaubaehn** [comment]
@markil01 
> No, I uploaded the NHS certificate before the 2.7.1 release

Thanks, I got it now!

@dsarkar Big thank you to you for providing information so quickly!

@My1 
> at least the swiss app actually tells you this compared to the CovPassCheck which tells you practically nothing

This is intended because of data privacy ("Datenschutz"): The verifier shall not receive any information _why_ the certificate is invalid, or what kind of certificate it is actually, because this reveals more information about the presenting person, than is necessary to do the job as gate keeper. For this purpose, only binary data "valid/invalid" would be enough.
For my taste, it's also a bit too restrictive.

About the NHS issue in general: I'm a bit shocked and sad that NHS is not yet fully participating. Without following these issues before, I had a kind of expectation (or: wishful thinking) that NHS was fully integrated. Let's hope that this can be achieved soon.

**Comment by MikeMcC399** [comment]
NHS England's page on https://www.nhs.uk/conditions/coronavirus-covid-19/covid-pass/ describes certificates similar to EU Digital COVID certificates, but they are not identical. There are links at the bottom of that page to Scotland, Wales and Northern Ireland. Hopefully they can all be made interoperable with the EU scheme.

Apart from the EU countries, https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en shows Iceland, Liechtenstein, Norway, San Marino, Switzerland & Vatican City, but not the United Kingdom currently participating in the EU Digital COVID certificates scheme.
