### ISSUE TITLE
App already shows fully vaccinated on day 14 after the last shot

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#638]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) - Currently checking
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Requested
- Android version: 11
- App version: 2.3.3

## Describe the bug

The app already shows the "Fully vaccinated" tile on the Home Screen on day 14 and not only at day 15.
This leads to the problem that the user is seeing the fully vaccinated tile but the CovPassCheck App still shows that the certificate is not valid yet. It says that the full vaccination status will be archived on the next day.

## Steps to reproduce the issue

1. Register a vaccination certificate
2. Wait till you reached day 14 after your last shot
3. See that CWA already shows "Fully vaccinated"
4. See that CovPassCheck shows that you don't yet have a valid vaccination certificate.

## Expected behaviour

Fully vaccinated tile should only be shown starting on day 15 after the vaccination.

## Additional context

1. This is a report I did based on Feedback on [Twitter](https://twitter.com/AndreasPechtold/status/1403597056510410752). 
2. I'm checking the behavior under iOS, but I can't find a test QR-Code which has received all shots but the vaccination is not yet 14 days ago, do you have a QR-Code for me from which I could test this?

---
Internal Tracking ID: [EXPOSUREAPP-7831](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7831) iOS
Internal Tracking ID: [EXPOSUREAPP-7865](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7865) Android

**Comment by dsarkar** [comment]
Thanks everybody for reporting here. Similar report on AppStore therefore transferred to doc repo.


---
Internal Tracking ID: [EXPOSUREAPP-7831](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7831)
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 
I looked at the Android test [VaccinatedPersonTest.kt](https://github.com/corona-warn-app/cwa-app-android/blob/e7513fe5f56b258e3ebf9f701b64292da065cfd6/Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPersonTest.kt#L77-L100). It uses a vaccination date of 2021-04-27 and says at 2021-05-10T12:00:00.000Z that the result is COMPLETE vaccination and at 2021-05-11T12:00:00.000Z the result is IMMUNITY.

Date | Days since vaccination | CWA Result
--- | --- | ---
2021-04-27 | 0 | COMPLETE 
2021-04-28 | 1 | COMPLETE
2021-04-29 | 2 | COMPLETE
2021-04-30 | 3 | COMPLETE
2021-05-01 | 4 | COMPLETE
2021-05-02 | 5 | COMPLETE
2021-05-03 | 6 | COMPLETE
2021-05-04 | 7 | COMPLETE
2021-05-05 | 8 | COMPLETE
2021-05-06 | 9 | COMPLETE
2021-05-07 | 10 | COMPLETE
2021-05-08 | 11 | COMPLETE
2021-05-09 | 12 | COMPLETE
2021-05-10 | 13 | COMPLETE
2021-05-11 | 14 | IMMUNITY
2021-05-12 | 15 | IMMUNITY

This does not agree with the definition provided by https://digitaler-impfnachweis-app.de/faq/ from the Robert Koch-Institut. 

"Der volle Corona-Impfschutz ist erst 14 Tage nach der letzten erforderlichen Impfung erreicht. Der QR-Code als Nachweis für den kompletten Impfschutz ist daher erst ab Tag 15 nach der vollständigen Corona-Impfung gültig."

In dem obigen Beispiel wird die vollständige Corona-Impfung am 27.04.2021 durchgeführt. Tag 1 nach der vollständigen Impfung ist wohl 28.04.2021, daher ist logischerweise Tag 15 nach der vollständigen Impfung 12.05.2021 und nicht 11.05.2021. IMMUNITY sollte erst ab 12.05.2021 gezeigt werden und nicht schon am 11.05.2021.

CWA und die Definition sind nicht in Einklang miteinander.

(I wrote in German since this is an interpretation of a rule written in German and I didn't want to introduce translation interpretations into the analysis.)

**Comment by MikeMcC399** [comment]
@guruguruguru 
Thanks for adding your observations!

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thank you so much for your investigation! I'll look at the iOS code when I find the time to do. 

> Can you provide for your examples the concrete date of vaccination and the display date in the app?

These are the screenshots from the [Twitter](https://twitter.com/AndreasPechtold/status/1403597056510410752) user: 

| CWA showing immunity too early (12.06.) | CovPass shows when the certificate becomes valid | CovPasCheck shows that the certificate is invalid |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/67682506/121890954-3744d100-cd1b-11eb-9162-17d72372f764.jpeg) | ![image](https://user-images.githubusercontent.com/67682506/121890977-3ad85800-cd1b-11eb-9d4e-b6eaa131acc9.jpeg) | ![image](https://user-images.githubusercontent.com/67682506/121890986-3f9d0c00-cd1b-11eb-8377-c9a06dfaddbd.jpeg)|

**Comment by Ein-Tim** [comment]
Maybe related here: https://github.com/Digitaler-Impfnachweis/certification-apis/issues/91

**Comment by MikeMcC399** [comment]
I found https://www.bundesanzeiger.de/pub/publication/x6tHxtuQ0pora3FnUEG/content/x6tHxtuQ0pora3FnUEG/BAnz%20AT%2008.05.2021%20V1.pdf?inline with the definition

3. ein Impfnachweis ein Nachweis hinsichtlich des Vorliegens einer vollständigen Schutzimpfung gegen das Coronavirus SARS-CoV-2 in deutscher, englischer, französischer, italienischer oder spanischer Sprache in verkörperter
oder digitaler Form, wenn die zugrundeliegende Schutzimpfung mit einem oder mehreren vom Paul-Ehrlich-Institut
im Internet unter der Adresse www.pei.de/impfstoffe/covid-19 genannten Impfstoffen erfolgt ist, und
a) entweder aus einer vom Paul-Ehrlich-Institut im Internet unter der Adresse www.pei.de/impfstoffe/covid-19
veröffentlichten Anzahl von Impfstoffdosen, die für eine vollständige Schutzimpfung erforderlich ist, besteht
und seit der letzten erforderlichen Einzelimpfung mindestens 14 Tage vergangen sind oder
b) bei einer genesenen Person aus einer verabreichten Impfstoffdosis besteht,

So according to this, CWA is proclaiming immunity one day too early.

Since there is no time-stamp, only a date, on the vaccination certificate, we have to assume that the vaccination takes place late on day 0. So to ensure that at least 14 full days have past, we have to wait for days 1 to 14 to pass. Only on day 15 can we say that a person is immune.

**Comment by bartim** [comment]
This line seems to be doing the calculations for the iOS app: 

https://github.com/corona-warn-app/cwa-app-ios/blob/b28ef6f0898064bbc86788d91c366e252a87952e/src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/HealthCertifiedPerson.swift#L115

Looks like iOS also calculates immunity one day early. But I am not a Swift guy, so take this with a grain of salt.

**Comment by MikeMcC399** [comment]
@dsarkar 

Is there any dev feedback to Internal Tracking ID: [EXPOSUREAPP-7831](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7831) yet?

This seems quite a visible issue even though the issue resolves itself one day later for an individual when all apps then deliver the same result. Is it considered high priority to resolve, perhaps also if necessary in a hotfix to 2.3.x?

**Comment by Geimpfter** [comment]
> Looks like iOS also calculates immunity one day early. But I am not a Swift guy, so take this with a grain of salt.

Yes, I have the same issue on my iphone and on my android.

**Comment by MikeMcC399** [comment]
@dsarkar 
Getting feedback on this issue to say whether it is a bug or not and when (if a bug) it will be fixed, is more about the reputation of the app for providing correct information than anything else. So I think responding to the issue should be treated urgently.

The consequence for the person owning the vaccination certificate receiving immunity status one day too early is in favor of the vaccinated person. That should not be a worry in itself.

The consequence for people who the person owning the vaccination certificate might be allowed to come into contact with, one day too early, is negative, however the difference in the risk of infection between the 14th and the 15th day after vaccination is going to be extremely small. The legal definition of 14 days is also an arbitrary length of time to say that the risk is acceptable.

So this is about reputation and reliability of the app. I hope there will soon be a response to this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks..... this snowed under, I will forward your info now. Thanks!

**Comment by dsarkar** [comment]
FYI this matter is set to "very high" priority

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-7831](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7831) iOS
Internal Tracking ID: [EXPOSUREAPP-7865](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7865) Android

**Comment by dsarkar** [comment]
FYI PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/2950

**Comment by dsarkar** [comment]
FYI PR Android https://github.com/corona-warn-app/cwa-app-android/pull/3467

**Comment by MikeMcC399** [comment]
It's good to see that the issue has already been fixed in Android and iOS and will be ready for release together with version 2.4.x. 👍🏻

**Comment by lumaxis** [comment]
> I looked at the Android test [VaccinatedPersonTest.kt](https://github.com/corona-warn-app/cwa-app-android/blob/e7513fe5f56b258e3ebf9f701b64292da065cfd6/Corona-Warn-App/src/test/java/de/rki/coronawarnapp/vaccination/core/VaccinatedPersonTest.kt#L77-L100). It uses a vaccination date of 2021-04-27 and says at 2021-05-10T12:00:00.000Z that the result is COMPLETE vaccination and at 2021-05-11T12:00:00.000Z the result is IMMUNITY.
> 
> Date	Days since vaccination	CWA Result
> 2021-04-27	0	COMPLETE
> 2021-04-28	1	COMPLETE
> 2021-04-29	2	COMPLETE
> 2021-04-30	3	COMPLETE
> 2021-05-01	4	COMPLETE
> 2021-05-02	5	COMPLETE
> 2021-05-03	6	COMPLETE
> 2021-05-04	7	COMPLETE
> 2021-05-05	8	COMPLETE
> 2021-05-06	9	COMPLETE
> 2021-05-07	10	COMPLETE
> 2021-05-08	11	COMPLETE
> 2021-05-09	12	COMPLETE
> 2021-05-10	13	COMPLETE
> 2021-05-11	14	IMMUNITY
> 2021-05-12	15	IMMUNITY
> This does not agree with the definition provided by https://digitaler-impfnachweis-app.de/faq/ from the Robert Koch-Institut.
> 
> "Der volle Corona-Impfschutz ist erst 14 Tage nach der letzten erforderlichen Impfung erreicht. Der QR-Code als Nachweis für den kompletten Impfschutz ist daher erst ab Tag 15 nach der vollständigen Corona-Impfung gültig."
> 
> In dem obigen Beispiel wird die vollständige Corona-Impfung am 27.04.2021 durchgeführt. Tag 1 nach der vollständigen Impfung ist wohl 28.04.2021, daher ist logischerweise Tag 15 nach der vollständigen Impfung 12.05.2021 und nicht 11.05.2021. IMMUNITY sollte erst ab 12.05.2021 gezeigt werden und nicht schon am 11.05.2021.
> 
> CWA und die Definition sind nicht in Einklang miteinander.
> 
> (I wrote in German since this is an interpretation of a rule written in German and I didn't want to introduce translation interpretations into the analysis.)

Sorry in advance for bringing this up so late in the process but I just started thinking about a bit this after a quick discussion on Twitter with @Ein-Tim and others.
I personally think the new interpretation of how to count the days is not correct and actually the previous logic was already right.

Quoting https://www.rki.de/SharedDocs/FAQ/COVID-Impfen/FAQ_Liste_Durchfuehrung_Impfung.html#FAQId15234274: 

> Als vollständig geschützt gelten Personen 14 Tage nach Verabreichung aller notwendigen COVID-19-Impfstoffdosen, also am 15. Tag. 

So a person is considered "fully protected" 14 days after the second dose, on the 15th day.

If you focus on "15. Tag" (15th day), that leaves room for interpretation, depending on if you consider the day of the vaccination the "zero-th" day or the "first day". However, if we focus on "14 days after the second dose", it becomes much more clear:

If I got my second dose on 04-27, 04-28 would be "1 day after second dose", i.e. 05-11 is "14 days after second dose" (as is shown in your table) which from my interpretation fulfill's the criteria as specified by the RKI.
This by deduction means that the "15th day" must be counted with the day of the vaccination being considered the "1st day"

**Comment by MikeMcC399** [comment]
@lumaxis 

You can read the legal text quoted on http://www.pei.de/impfstoffe/covid-19:

"... und seit der letzten erforderlichen Einzelimpfung mindestens 14 Tage vergangen sind ..."

I explained in https://github.com/corona-warn-app/cwa-documentation/issues/638#issuecomment-860655241 how I interpreted this, and implicitly the Open Source Team agrees with this because they have changed the app accordingly in preparation for the 2.4 release. The CovPass app was already calculating this way.

You have a different interpretation which depends on counting at the beginning of the day instead of the end of the day. To a certain extent this is all arbitrary anyway, but at least all apps should be consistent.

When CWA 2.4 is released we can say that CWA and CovPass will be in agreement and that will help remove some confusing experiences for users of the current CWA 2.3 version.

**Comment by bartim** [comment]
@lumaxis

Also, §§ 186 ff. BGB are relevant here.

§ 187 Abs. 1 Alt. 1:
> Ist für den Anfang einer Frist ein Ereignis _[...]_ maßgebend, so wird bei der Berechnung der Frist der Tag nicht mitgerechnet, in welchen das Ereignis _[...]_ fällt.

This also seems to imply that the solution the CWA has now adopted is the correct one.

**Comment by Geimpfter** [comment]
@lumaxis 
doctors and bureaucrats think differently.

From a medical point of view (for example when it comes to setting the date of the second vaccination) 14 days later would be day 14 and not day 15! Doctors don't take the exact time into account when calculating the intervals, since vaccinations are usually given during normal opening hours and not in the middle of the night. In addition, a few more or less hours do not matter at all.

Vaccine studies show that effectiveness begins after 10-12 days. This is also the time when the shift from IgM to IgG antibodies (measurable in laboratories) takes place. RKI has probably rounded up to two weeks in order to have an interval that is easier to count on the calendar and two more days for safety.

If you look at this from a legal point of view, the immunity defined by the RKI begins after 14 days, i.e. 336 hours and no second before! Since the exact time is not recorded, one can even construct the extreme case that someone is vaccinated at 23 clock and wants to enter a nightclub at midnight on the 14th day. Then only 13 days and 1 hour would have passed and this is nearly one day too early!

totally petty, but correct.

**Comment by lumaxis** [comment]
Thanks for the explanations, everyone! 🙂 

> "... und seit der letzten erforderlichen Einzelimpfung mindestens 14 Tage vergangen sind ..."

I think this way of phrasing it makes it much more clear and also intuitively makes sense when you think about it in that way.
"Wait at least 15 days to ensure at least 14 days have passed, even if someone was vaccinated at 23:59 on day 0", which I believe is also what @Geimpfter was hinting at.

> To a certain extent this is all arbitrary anyway, but at least all apps should be consistent.

This we can definitely all agree on and to me is by far the most important aspect anyway. 💯 
Thanks again for indulging me and discussing this a bit more and thanks everyone for the work you do on the app! 🙇🏼

**Comment by Ein-Tim** [comment]
Version 2.4 has just been released and is in staged rollout! It would be nice if someone could confirm the fix before I close this issue. Thanks!

**Comment by Ein-Tim** [comment]
@krausf confirmed the fix under iOS in https://github.com/corona-warn-app/cwa-app-ios/issues/3008#issuecomment-868327015.

Can someone confirm the fix under Android?

**Comment by guruguruguru** [comment]
I Just got 2.4.2.
My second dose was on 13.06.2021 12:59 and the app says  "vollständiger Impfschutz in 1 Tag".
I would have expected to be fully protected on Monday (2 days)

**Comment by dsarkar** [comment]
@guruguruguru Which version are you using? R 2.3 or R 2.4? Under R 2.4 it will take one more day to show full immunisation.

**Comment by guruguruguru** [comment]
As I wrote, Version is 2.4.2

**Comment by Ein-Tim** [comment]
@guruguruguru 

Could you maybe keep watching the behavior and report back what happens tomorrow (whether the app really shows the "Vollständiger Impfschutz" card tomorrow).

Also, could you maybe scan the QR-Code with the CovPass App and see what date it shows?

**Comment by MikeMcC399** [comment]
@guruguruguru 
> I Just got 2.4.2.
My second dose was on 13.06.2021 12:59 and the app says "vollständiger Impfschutz in 1 Tag".
I would have expected to be fully protected on Monday (2 days)

Could you say whether you are using Android or iOS?

I suspect it is Android and that the countdown code was not changed only the status code. I think that the Android 2.4.2 app will show you the tick mark for "Digitaler Impfnachweis" correctly on June 28, 2021 (and not on June 27, 2021).

If I am right and you are seeing the problem on Android, I suggest that you open a separate Bug Report issue in the [Android repository](https://github.com/corona-warn-app/cwa-app-android/issues/new/choose).

**Comment by guruguruguru** [comment]
Hi, yes this is Android. I will come back to you tomorrow/monday to Update you on the behaviour.

**Comment by guruguruguru** [comment]
So today it says "Impfschutz in 0 Tagen vollständig"

So it seems to be correct as it seems to switch to fully protected tomorrow but the output should be changed to the correct value as well

**Comment by Ein-Tim** [comment]
@guruguruguru 

Could you please open a new issue for the "0 days issue"? 
I would suggest to open it in the respective repo (iOS or Android - depending on what OS you are using). 
However, the devs should try to reproduce the issue on both OS.
That would be fantastic! Thank you!

**Comment by thomasaugsten** [comment]
I asume it is android I created a JIRA Ticket EXPOSUREAPP-8121

**Comment by guruguruguru** [comment]
@thomasaugsten So I do not need to file another issue, right?

**Comment by Ein-Tim** [comment]
I would still like to have a separate GitHub Issue to track this bug. Also to make sure it does only affect Android.

I would consider this issue I reported here (in the OP) as solved, so I will close this issue now.

Closing as fixed in version 2.4.

**Comment by DerVogel2020** [comment]
@thomasaugsten  I can confirm that it's a bug at least under android. Before and after the update the counter shows the same value (in my case "1").
Before update (2.3):
![Screenshot_20210627-070840_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/123542156-43338880-d748-11eb-8aab-9a0c6119b37b.jpg)
![Screenshot_20210627-070900_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/123542162-49c20000-d748-11eb-8323-13858868f853.jpg)

After the update (2.4):
![Screenshot_20210627-130218_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/123542167-534b6800-d748-11eb-916e-68a316ca5371.jpg)
![20210627_130248.jpg](https://user-images.githubusercontent.com/65366950/123542170-58a8b280-d748-11eb-835c-c85f9c6346b3.jpg)

**Comment by Ein-Tim** [comment]
FYI everybody (especially @DerVogel2020 & @guruguruguru), I opened https://github.com/corona-warn-app/cwa-app-android/issues/3561 to track the "0 days issue".

**Comment by DerVogel2020** [comment]
> FYI everybody (especially @DerVogel2020 & @guruguruguru), I opened https://github.com/corona-warn-app/cwa-app-android/issues/3561 to track the "0 days issue". Feel free to add your observations there.

Thanks. Will report there.
