### ISSUE TITLE
Unprotected sneeze when passing other person

### ISSUE THREAD

**Issue by quaddy-services** [corona-warn-app/cwa-documentation#64]
Additional to the default contact warning (15 minutes near 1 m or whatever will be defined)
the App must have an short contact mode
to visualze when I had short contact to an (later on detected) infected person, 
e.g. when walking around and getting some virus via unprotected sneeze when passing other person, and so I am 
probably infected as well (or at least should contact Gesundheitsamt to become tested).

**Comment by niklas2810** [comment]
The API will be provided by Google and Apple and does not allow such use cases (if i understand the structure correctly), because the surrounding cryptographic keys are polled in a fixed time interval. Even if that was possible (e.g. by decreasing this interval), I would argue that such messages would cause unjustified unsettlement and should only be sent when a user had long contact with an infected person. Especially when considering that the probability that the infected person sneezed right next to you is quite low, I doubt the effeciency of that feature.

**Comment by tklingbeil** [comment]
@niklas2810 I agree! The [Bluetooth Specification](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-BluetoothSpecificationv1.2.pdf) currently defines a "minimum periodic sampling every 5 minutes".

Even if you had shorter sampling intervals, you would need to let the app know, that such an incident has just happened. Otherwise, you might risk getting a lot more false positives.
