### ISSUE TITLE
Unable to Scan Luca QR Code

### ISSUE THREAD

**Issue by BoBiene** [corona-warn-app/cwa-documentation#658]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12
- iOS/Android version: iOS 14.6
- App version: 2.4.2

## Describe the bug

Several times in the past it has been reported that it will be possible to use the luca generated QR code to check-in to a location. Until now I'm not able to use this feature.

## Steps to reproduce the issue

Try to check-in to a location with a luca generated QR code.

## Expected behaviour

Luca generated QR Codes must be compatible.

**Comment by heinezen** [comment]
Hello @BoBiene 

What @Ein-Tim says is correct. Luca QR codes currently cannot be scanned by the CWA due to security requirements (see https://github.com/corona-warn-app/cwa-server/pull/1362#issuecomment-861228455)

> Because of the security requirements of this merged QR-Codes are still discussions ongoing. The security requirements are necessary to prevent deanonymization of the CWA users.

We will close your issue in favor of https://github.com/corona-warn-app/cwa-documentation/issues/590

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@BoBiene FYI https://www.coronawarn.app/de/faq/#check_in_luca
