### ISSUE TITLE
Bad behavior when adding local incidence without network access

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-documentation#672]
### Describe the bug

Adding a new local incidence while the device is not connected to the network causes the application to behave badly.

### Steps to reproduce the issue

1. Disconnect device from internet
2. Add new Local 7-Day Incidence

The newly added incidence card is not shown at all. No indication that the operation was successful is given.

3. Reconnect the device to the internet.
4. Close and reopen application (recreate activity).

The newly added incidence card is now displayed with up-to-date values.

### Expected behaviour

Indicate success of the operation even if no internet connection is available.

### Possible Fix

The card should be displayed with no value, for example with a `–` character instead of a value, to indicate that the data is not yet available due to missing internet access.

### Additional context

The other statistic cards are not shown either if the data has not been loaded yet, for example if the app data had been wiped and the device had not been connected to the internet.

---
Internal Tracking ID: [EXPOSUREAPP-8733](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8733)
Internal Tracking ID: [EXPOSUREAPP-8436](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8436)

**Comment by dsarkar** [comment]
@fynngodau @Ein-Tim Thanks for reporting.  Internal Tracking ID: [EXPOSUREAPP-8733](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8733)


---
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
Android PR: https://github.com/corona-warn-app/cwa-app-android/pull/3815

(Thanks for the ping @vaubaehn)

**Comment by Ein-Tim** [comment]
I can confirm that the behavior under iOS has improved with version 2.7.

Adding a local 7-day incidence without internet connection now no longer just does nothing while offline but already adds the card to the Home Screen. However, the card is empty (because CWA couldn't download the incidence from the internet - makes sense)
Here's a screenshot:
<img src="https://user-images.githubusercontent.com/67682506/129546599-9c0cda04-ad51-4375-a2f4-a15666b21d85.PNG" width="300">

After connecting to the internet, closing and reopening the app, the value is shown:
<img src="https://user-images.githubusercontent.com/67682506/129546774-cfc71136-5b40-45a1-b23e-8ccc794fe9a0.PNG" width="300">

**Comment by MikeMcC399** [comment]
The behaviour under Android 2.7.1 differs to under iOS. If there is no internet connection, the message:

`statistics_add_card_warning_no_internet`
is output:

DE
"Ihre Internetverbindung wurde unterbrochen. Hinzufügen einer 7-Tage-Inzidenz nicht möglich. Bitte prüfen Sie die Verbindung und versuchen Sie es erneut."

EN
"Your Internet connection was lost. It was not possible to add a 7-day incidence figure. Please check the connection and try again."

The English translation is however inaccurate. "It was not possible to add a 7-day incidence figure." says to me that an attempt was made to add a a 7-day incidence figure and it failed. In fact all I have done is to swipe onto the tile to add a 7-day incidence figure, but I haven't selected a geography to add (because none was displayed to select from). 

It makes more sense in this context to say "It is not possible to add a 7-day incidence figure." (present tense: is, not past tense: was).


Apart from that minor text point, the issue is resolved on Android 2.7.1. It is not possible to add a local 7-Day Incidence under Android with no Internet connection. The situation no longer arises that the location is added without feedback that the operation was successful when there was no Internet connection. When Internet connection is restored the tile refreshes and it is then possible to request "Add Local 7-Day Incidence".

**Comment by Ein-Tim** [comment]
@MikeMcC399 I'll add an issue to the iOS repo requesting to add this message to iOS too.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I'll add an issue to the iOS repo requesting to add this message to iOS too.

That seems unnecessary if iOS allows adding a local 7-Day incidence without an Internet connection.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Although it does allow to add the card, the card can be empty. And IHMO, this is more confusing than just showing a warning message.

**Comment by Ein-Tim** [comment]
@fynngodau Do you consider this issue as fixed? If yes I'd suggest to close this issue.

**Comment by fynngodau** [comment]
The behavior is still not optimal when the network connection disappears while the region selector is open, but the core problem is tackled, I suppose.

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-ios/pull/5018
