### ISSUE TITLE
Untrue statement in "How exposure logging works" section in Exposure Logging settings

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#680]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Any
- iOS/Android version: Any
- App version: 2.6.3 (iOS)

## Describe the bug

The app contains this text in the "How exposure logging works" section in the Exposure Logging settings ([Screenshot](https://user-images.githubusercontent.com/67682506/128737109-cfb6882d-d67b-4001-9b81-887c5e389eb9.jpeg)):

`The app never collects personal data such as your name, address or location, nor is this information passed on to other users. It is not possible to use random IDs to draw conclusions about individual persons.`

This text is not true (anymore), since the app can collect personal data such as your name and/or address if you
1. Add an EU digital COVID certificate to the app (fully possible since CWA version 2.5)
2. Create an Rapid Test Profile (possible since CWA version 2.2)
3. Receive a personalized rapid antigen test result in the app (possible since CWA version 2.1)
4. Create a EU digital COVID certificate for a test result in the app (possible since CWA version 2.4)

The text was not changed with the updates which added the above mentioned features.

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. On the top, tap on "Exposure Logging Active/Stopped" 
3. Scroll to the very bottom
4. See the untrue statement in the last paragraph

## Expected behaviour

The text should not make untrue statements.

## Possible Fix

Correct the texts here:

iOS: https://github.com/corona-warn-app/cwa-app-ios/blob/66060820e179116bea7b31d35d6fc81855022aee/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L1023 
Android: https://github.com/corona-warn-app/cwa-app-android/blob/fc7c1bd7377a9db04cb50abc06588c1d93400041/Corona-Warn-App/src/main/res/values/strings.xml#L581

The text could be changed to something like:

`The exposure logging feature of the app never collects personal data such as your name, address or location, nor is this information passed on to other users. It is not possible to use random IDs to draw conclusions about individual persons.`

---
Internal Tracking ID: [EXPOSUREAPP-8915](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8915)

**Comment by dsarkar** [comment]
@Ein-Tim Ok, see your point: Internal Tracking ID: [EXPOSUREAPP-8915](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8915). Thanks.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/3344

**Comment by Ein-Tim** [comment]
I can confirm that this has been fixed in version 2.8 under iOS.
Awaiting confirmation of fix under Android before closing.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Could you confirm that this has been fixed in version 2.8 under Android?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

In CWA Android 2.8.0 the sentence is fixed:

"Personal data, such as your name, address, or location, is never recorded **during exposure logging**, nor is this information passed on to other users."

Here is the full string:

https://github.com/corona-warn-app/cwa-app-android/blob/d74e5805be8355e000d1cfb9655eb7e857438ccf/Corona-Warn-App/src/main/res/values/strings.xml#L586-L587

<string name="settings_tracing_body_text">"You need to enable the exposure logging feature so that the app can determine whether you are at risk of infection. The exposure logging feature works transnationally, meaning any possible exposure involving users is also detected by other official coronavirus apps.\n\nThe exposure logging feature works by your Android smartphone receiving encrypted random IDs from other app users via Bluetooth and passing your own random IDs to their smartphones. Every day, the app downloads lists containing the random IDs – along with any voluntary information about the onset of symptoms – of all users who have tested positive for the virus and voluntarily shared this information (specifically: their random IDs) via their app. This list is then compared with the random IDs of other users you have encountered that have been recorded by your Android smartphone, in order to calculate the likelihood that you have also been infected and to warn you if necessary.\n\nYou can use the toggle switch to disable exposure logging at any time.\n\nPersonal data, such as your name, address, or location, is never recorded during exposure logging, nor is this information passed on to other users. It is not possible to use random IDs to draw conclusions about individual persons."</string>

---

You should be able to close the issue now.

**Comment by Ein-Tim** [comment]
Thanks for the confirmation @MikeMcC399! 

Closing this issue as fixed.
