### ISSUE TITLE
How do you notify about fake certificates?

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-documentation#751]
## Where to find the issue
Release 2.13.2 apparently checks that a certificate has not been revoked. 
The Adolf Hitler and Mickey Mouse certificates are still importable over a month after being made public.

https://www.zerozone.it/cybersecurity/e-se-spunta-fuori-il-green-pass-di-adolf-hitler/20305

## Describe the issue
How can you report a rogue certificate? That’s not documented anywhere as far as I could see.

## Suggested change
Describe the process for reporting rogue certificates in the FAQ.

**Comment by MikeMcC399** [comment]
@alanrick 
1. Could you edit the title which currently says "How do you not"? It looks like you were interrupted whilst writing.
2. You also have a duplicate under https://github.com/corona-warn-app/cwa-documentation/issues/750, so maybe you could close the other one.
3. You refer to 2.13.2 so I presume you are referring to iOS, because Android is 2.13.3 for this functionality.
4. If there is going to be some advice published about how to report forgeries, then it would be quicker to publish it in the FAQs.

**Comment by alanrick** [comment]
1. I was indeed.  
2. closed. Didn’t even notice it was created. 
3. Yes, iOS
4. I agree. Then the OS is irrelevant. I’ll change the description.

**Comment by thomasaugsten** [comment]
Regarding digital covid certificates please use the contacts from covpass
https://digitaler-impfnachweis-app.de/kontakt
