### ISSUE TITLE
How to remove rapid test results from the contact journal?

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-documentation#760]
According to the privacy policy, it is possible to remove rapid test results from the contact journal at any time.

https://github.com/corona-warn-app/cwa-app-android/blob/97649aa4105ffa69c102a6add1e695e5b8832b37/Corona-Warn-App/src/main/assets/privacy_de.html#L557

However, I could not find out how this can be done.

It this is not implemented in the app, it should be removed from the privacy policy.

---
Internal Tracking ID: [EXPOSUREAPP-10745](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10745)

**Comment by dsarkar** [comment]
@fynngodau @Ein-Tim Thanks, stand by for answer.

**Comment by dsarkar** [comment]
@fynngodau @Ein-Tim For the moment we consider this as a text-issue. Internal Tracking ID: [EXPOSUREAPP-10745](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10745)

**Comment by dsarkar** [comment]
related tickets:
Internal Tracking ID: [EXPOSUREAPP-10171](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10171) Android
Internal Tracking ID: [EXPOSUREAPP-10173](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10173) iOS

**Comment by dsarkar** [comment]
FYI

![image](https://user-images.githubusercontent.com/1409741/144040411-e2ad5d60-8f60-4245-83d5-a2afe3a2c3bd.png)

https://github.com/corona-warn-app/cwa-app-ios/pull/3908

**Comment by Ein-Tim** [comment]
Confirm fixed in 2.15.1 under iOS:

<img src="https://user-images.githubusercontent.com/67682506/147421968-bc69592a-da2f-400a-9eb5-dd23c12193c2.jpeg" width="300">

**Comment by dsarkar** [comment]
EN iOS Fix confirmed in 2.15.1

![image](https://user-images.githubusercontent.com/1409741/147560652-dac6caa1-750e-4f11-8b27-3af44dca1cf3.png)

**Comment by MikeMcC399** [comment]
- This issue was resolved in CWA Android through PR https://github.com/corona-warn-app/cwa-app-android/pull/4460 for version 2.15, which was released on Dec 20, 2021.

See https://github.com/corona-warn-app/cwa-app-android/blob/ebd4b26fb3eae73ded465909d2ae3fa718143cd3/Corona-Warn-App/src/main/assets/privacy_de.html#L844
"Die Schnelltest-Ergebnisse werden auch in Ihrem Kontakt-Tagebuch hinterlegt."

compared to previously where the text read:
"Die Schnelltest-Ergebnisse werden auch in Ihrem Kontakt-Tagebuch hinterlegt. Sie können diese
dort jederzeit wieder löschen."

It looks like this issue should be closed.

@fynngodau since this is your issue, maybe you'd like to double-check?

**Comment by fynngodau** [comment]
Thanks, I can confirm this to be fixed.
