### ISSUE TITLE
Legal term definition "Vollständig geimpft" (FAQ from RKI)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#815]
There were a couple of questions about the legal definition of "vollständig geimpft" and I wanted to cross-reference a new article from RKI about this definition.

**Wer gilt laut rechtlichen Verordnungen als vollständig geimpft bzw. genesen?**

"Die COVID-19-Impfung schützt vor COVID-19. Auch durch eine COVID-19-Erkrankung kann man einen Schutz vor COVID-19 aufbauen. Für den Status „vollständig geimpft“ und „genesen“ gelten verschiedene Bedingungen. Diese werden u.a. in der COVID-19-Schutzmaßnahmen-Ausnahmenverordnung (SchAusnahmV, § 2 Nummer 3) oder in der Coronavirus-Einreiseverordnung (CoronaEinreiseV, § 2 Nummer 10) festgelegt."

Use the link [COVID-19 und Impfen: Antworten auf häufig gestellte Fragen (FAQ)](https://www.rki.de/SharedDocs/FAQ/COVID-Impfen/gesamt.html) to read the whole article.

---

Note that on the RKI page [Digitales Impfquotenmonitoring zur COVID-19-Impfung](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html) the statistical term "Grundimmunisiert" is used in equivalence to the legal term "vollständig geimpft".

CC: @Jo-Achim and @Ein-Tim

---
Internal Tracking ID: [EXPOSUREAPP-11563](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11563)

**Comment by Jo-Achim** [comment]
@MikeMcC399, 
thank you for your work.

I'm guessing it's kind of a quick shot at the moment. And from my point of view, on closer reflection...

A **"basic immunization" ("Grundimmunisierung")** is easy to define by specifying how many doses of which vaccines are required, possibly in combination, and over what period of time.
From this "basic immunization" then further vaccinations are counted.

The term **"fully vaccinated" ("vollständig geimpft")** is more difficult. Because if you still need an additional 'booster' vaccination for the most complete possible vaccination protection, then "fully vaccinated" is actually a temporary term that is shifted by this with each additional / necessary vaccination. Also, since the 'additional' vaccinations cannot be done at the same time, the term "fully vaccinated" applies to those who have just been boosted and to those who are not yet allowed to be boosted. (Whether the last point is a problem in practice, we can safely leave open at this point.)

**My conclusion at the moment:** Perhaps one should avoid the term "fully vaccinated" and only use the term "basic immunization" for the above-mentioned condition of the first (2) vaccinations.

Otherwise it only remains to be seen until the RKI / PEI prescribe / use something else in the corresponding official regulations.
The other problem of the different uses of terms in the different previous documents will remain.

**Comment by MikeMcC399** [comment]
@Jo-Achim 

>  Perhaps one should avoid the term "fully vaccinated" and only use the term "basic immunization" for the above-mentioned condition of the first (2) vaccinations.

I agree that the term "fully vaccinated" is problematic and with hindsight should not have been used. 

Perhaps the lawmakers will modify the terms they use in the future, however for the moment the term is "hard-coded" into [COVID-19-Schutzmaßnahmen-Ausnahmenverordnung (SchAusnahmV, § 2 Nummer 3)](https://www.gesetze-im-internet.de/schausnahmv/BJNR612800021.html) where it says:
"Im Sinne dieser Verordnung ist ... ein Impfnachweis ein Nachweis hinsichtlich des Vorliegens eines vollständigen Impfschutzes gegen das Coronavirus SARS-CoV-2"

so this is the current status and use of the term in legal regulations.

For statistics, the use of the term can be avoided, however when legal points are involved, such as for travel or admission requirements, it makes more sense to use the same terms as the current regulations use, otherwise it might be even more confusing!

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11563](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11563)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@larswmh 
I don't think there is any special action necessary for this issue, apart from the separate issue:
- https://github.com/corona-warn-app/cwa-documentation/issues/816 for app changes

So I will close this issue.
