### ISSUE TITLE
How secondary/new phone is handled?

### ISSUE THREAD

**Issue by simontb** [corona-warn-app/cwa-documentation#82]
## What is missing
How to handle people with 2 phones or people buying a new phone.

## Why should it be included
I have two phones (one for work and a private one) and now ask myself what would happen if I install the app on both phones, as I don't carry both with me all the time. Would I be able to use the app on both phones and in case of a positive test result send a warning from both devices?

Another example that might need to trigger 2 warnings from one test: People buying a new phone. In case the local data can't be migrated from one device to another, it would be required to send the warning from both devices if the switch just recently happened.

I'm aware these are edge cases, but would be interesting in your opinion.

## Where should it be included
Scoping document and solution architecture.

**Comment by sventuerpe** [comment]
These are great questions. My gut feeling tells me that specific support for such situations may be deferred until a later version. However, it would probably be a good idea to estimate early how frequently the described cases occur and what impact they may have on the success and reliability of the system.

Perhaps some recommendations could be included in end user documentation as long as there are no technical solutions: What should I do if I use multiple devices? What should I do when I get a new device?

**Comment by tklingbeil** [comment]
If you would let people confirm their positive test on two phones (e.g. work and private) and upload both sets of diagnosis keys, you would create another issue: In situations where both phones have been carried along, other people would have been (from the framework's perspective) exposed to two different people, who have later tested positive. This would probably result in a higher calculated risk.

Our current assumption for the first version was:

- 1 Person --> 1 Phone --> 1 App
- 1 Test --> 1 QR-Code -> 1 Test Result --> 1 Upload (actually two if you count in the key of the current day, which is still valid - but that's a different story)

We are absolutely aware that this does not cover 100% of the cases.

**Comment by tkowark** [comment]
Thanks again for brining up these questions. I hope that @tklingbeil 's answer is sufficient for now. We'll keep this issue in mind, but for the first release, the assumptions above are our guiding principles.

**Comment by akuckartz** [comment]
> We'll keep this issue in mind, but for the first release, the assumptions above are our guiding principles.

Then please tag this issue accordingly ("keep in mind").

**Comment by MikeMcC399** [comment]
This issue is closed, however for cross-reference, please see https://www.coronawarn.app/en/faq/#test_multiple_devices

**How do I share a positive test result on multiple devices?**

"If you have more than one smartphone (e.g. work and private), we recommend that you install the CWA on your private device first. Also, when scanning QR codes and sharing a positive result, we recommend that you first use your private device. If you additionally want to share a positive result via your company device or any other additional smartphone, this can be done via a so-called TeleTAN. By contacting +49 800 7540002 with a positive test result, you will receive a 10-digit TAN with which the test result can also be registered in the app. Please note: The TAN number is only valid for one hour."

**Comment by MikeMcC399** [comment]
Also the question about a new device is answered in https://www.coronawarn.app/en/faq/#new_device

**What do I have to consider when switching to a new device?**

A backup of the old random IDs is unfortunately not possible, because the Exposure Notification API of Apple/Google does not allow the export of this data. To still be informed about possible risk encounters, we recommend that you keep a close view of the risk status on the old device for at least 14 days after you install the Corona Alert app on the new device. Please note the following instructions:

- Your old device must be able to perform regular checks for possible encounters. Therefore, leave the device permanently turned on and permanently connected to the Internet.
- Keep the old device in a stationary location, e.g., in a specific place in your apartment. If possible, place the device in listening or visual range so that you are alerted early by a notification of the app.
- Actively access the Corona-Warn-App on the old device at least once a day and check your risk status there.
- If you are tested for COVID-19 during these 14 days, enter the QR code on your new device. If the test result is positive, you should share the test result on both devices. For sharing a test result on multiple devices, please note [this](https://www.coronawarn.app/en/faq/#test_multiple_devices) FAQ entry.

After 14 days, your old device will no longer contain any relevant entries for risk assessment. You don't need to pay any further attention to the risk status on this device and can remove the Corona-Warn-App there.
