### ISSUE TITLE
On which variables is the assumption of "attenuation <50dB equals <2 meters" made?

### ISSUE THREAD

**Issue by rawern** [corona-warn-app/cwa-documentation#85]
## What is missing
In your [LIMITATIONS ](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#limitations) section of your solution_architecture.md you state the assumption, that an attenuation < 50dB means an distance less than 2 meters.

Can you be more precise on which variables do you come to this assumption?

My experience working with BLE-Beacons and measuring the distance vary dramatically based on environment (indoors, outdoors) and also from device (depending on antenna characteristic within the phone).

## Why should it be included
Measuring the distance between phones is fundamental for this project and "THE" main metric for the score. News and politics often refer to the app as "it constantly measures the distance to nearby phones with the same/compatible apps and notifies you if there where infected users nearby in the past". 

So the measurement should be understandable, the false positives and false negatives should be as minimal as possible. Otherwise the users won't accept this tool.

Of course there is a variance in accuracy, but if every device reports different values for the same condition, how can we base decisions on this?

**Comment by tklingbeil** [comment]
As you already mentioned, we cannot assume that the app is able to "measure a distance" from just the attenuation (i.e. reported transmit power - received signal strength). We can be relatively sure that if the attenuation is low, the two devices are pretty close to each other. Basically, other assumptions cannot be made from just the attenuation.

The 50dB threshold for the attenuation buckets is defined here: https://developer.apple.com/documentation/exposurenotification/enexposureinfo/3586325-attenuationdurations. This is meant to identify close contacts, so let's assume 2 meters is close.

**Comment by rklueber** [comment]
Attenuation and distance is a highly non linear relationship.

Two people hugging each other’s with phone in back pocket of the jeans or in purse might be equal attention as two people in safe distance holding their phones in their hands. 

The risk score model is IMHO to simple. Other features of the phone can be uses as well (screen on, light sensor, orientation, ...). 

If someone from the officials is interested, we made some measurements in big scale and are willing to share results. 

PM me.

**Comment by SebastianWolf-SAP** [comment]
As @tklingbeil already pointed to the source of the threshold due to the fact that this level is defined by the Exposure Notification Framework this question is out-of-scope for this project. 

@rklueber Please reach out to us via e-mail to corona-warn-app.opensource@sap.com if you want to discuss further details. Overall all involved parties are - of course - aware of this problem. It's already outlined in https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#limitations and was already discussed in several scientific publications. The article https://www.heise.de/ct/artikel/Wie-Tracing-Apps-Covid-19-bremsen-sollen-4704893.html (in German) also gives a nice overview. If you have much more, we are looking forward to your message.
