### ISSUE TITLE
Question reg. approval  of organizations willing to provide a validation service 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#885]
## Your Question
The latest information of certificate checks for ticket booking process was given by @GisoSchroederSAP in https://github.com/corona-warn-app/cwa-website/issues/2218#issuecomment-1094809124 and is the following:

> Strictly speaking, there is no provider that still offers such a validation service anymore.
>
> This status given, I don't expect any update on the topic anymore, at least not before the pandemic situation will be re-evaluated maybe in late summer or fall this year.

The latest update of the FAQ entry https://www.coronawarn.app/en/faq/results/#val_service_basics is the following:

>  In Germany, **no provider of an online verification service has been approved**. With version 2.15, however, the CWA is ready to support corresponding verification services.

However, one question remains: If there is an organization willing to provide a validation service right now, would they be approved, or to elaborate, would the "Certificate check for bookings" feature go live if a validation service is provided?

I'm interested in an answer to this question as this would clarify if the website should 
a) be updated to include a note that the feature is on ice and organizations can currently not apply to provide a validation service or 
b) be update to include contact details for organizations interested in providing a validation service.

---
Internal Tracking ID: [EXPOSUREAPP-12980](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12980)

**Comment by Ein-Tim** [comment]
@dsarkar / @larswmh 

Will you mirror this issue to JIRA?

**Comment by dsarkar** [comment]
@Ein-Tim question is forwarded.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
You've invented a new word: "approvement"!
I think you mean "approval".

**Comment by GisoSchroederSAP** [comment]
During the last months almost no movement happend here. Subsequently, I asked for clarification whether or not the validation feature is still in place. From what I know so far, there never _was_ nor _is_ a third-party willing to implement this kind of validation service.
While the app is generally capable to support this feature, it practically cannot be facilitated by anyone due to the missing providers. 
So, to answer the initial question politely: In theory, yes, the service could be implemented, could get approval and could be offered by a partner, but we do not see any ambitions in this direction since the feature was released.

Looking forward to the public discussion and decissions regarding the COVID-19 pandemic I suggest not to put further efforts in the documentation of a "dead end" service.
