### ISSUE TITLE
Question about number of people infected and number of people used CWA to warn others

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-documentation#887]
## Your Question
How is this possible:
![Screenshot_20220502-093039_Corona-Warn](https://user-images.githubusercontent.com/65366950/166201377-ffa76807-615f-41df-a0d3-96a2df233d11.jpg)
![Screenshot_20220502-093045_Corona-Warn](https://user-images.githubusercontent.com/65366950/166201380-310a8b01-1d5a-4cfd-8510-e6dc524321b2.jpg)

In the last weeks, always about 20% of the infected people used the CWA to warn others. Now the factor swapped.

**Comment by Ein-Tim** [comment]
This is possible as people were tested positive but the health authorities don't report the positive tests to the RKI. Also, only because a new infection was reported yesterday, a person warning via CWA must not be tested positive yesterday.

**Comment by GisoSchroederSAP** [comment]
I'd like to support the reasoning by @Ein-Tim (thanks!). 
The number of confirmed new infections and warning persons is _not linked by date_ . An infected person may have received the positiv test result 10 days ago but might decide to warn other only later ("manually", leveraging a teleTAN) due to personal or technical reaons. So even when there are no infected persons reported, still there might be persons warning others.

On the other hand: Yes, our observation and the data donations indicate that the persons still using the CWA might be "convinced and supporting" users of our app. The ratio of warning persons increased significantly over the last 3 months and seems to be on an >70% score, which is quite a success.

![image](https://user-images.githubusercontent.com/69585203/166220213-847e2014-e81e-4071-b4aa-28a8156280b9.png)

**Comment by MikeMcC399** [comment]
According to https://www.n-tv.de/panorama/Podcast-Wieder-was-gelernt-So-vage-sind-Deutschlands-Corona-Zahlen-article23223791.html Rapid Antigen Tests are not counted in the infection statistics. 

According to https://www.coronawarn.app/en/faq/results/#rapid_antigen_test Rapid Antigen Tests can be used to warn others, if a positive test result is delivered in the app.

So apart from the difference in the days, the two figures (Bestätigte Neuinfektionen and Warnende Personen) are not directly comparable due the respective exclusion and inclusion of RATs.

The Sharing behaviour graph on https://www.coronawarn.app/en/analysis/ shows a heavy daily variation depending on the day of the week. (select Last 28 days, Daily, de-select QR code and teleTANs to show Total only)

![image](https://user-images.githubusercontent.com/66998419/166226173-436f29c9-c563-41b2-8866-5b9a6be28ad9.png)

**Comment by DerVogel2020** [comment]
Thanks for the answers.
