### ISSUE TITLE
place of meeting

### ISSUE THREAD

**Issue by bernienightscout** [corona-warn-app/cwa-documentation#904]
hello,

it would be good if one would get communicated to the place of encounter

**Comment by Ein-Tim** [comment]
Hey @bernienightscout,

thank you for opening this issue!

Please take a look at the blog post [Why doesn't the Corona-Warn-App show the exact time and place for a red risk tile encounter?](https://www.coronawarn.app/en/blog/2022-01-21-cwa-uhrzeit-rote-kachel/).

It explains why this is not possible.

I suggest to close this issue, as it is not possible to implement this feature.

**Comment by dsarkar** [comment]
@bernienightscout Thanks for your suggestion. @Ein-Tim already linked the relevant blog on this topic. In short, such feature cannot be implemented, due to high privacy concerns, and ultimately it is technically not possible due to limitations of the implementation of the so called ENF. This ENF is provided by the operating system and not port of the Corona-Warn-App, which makes use of it for the contact tracing. 


Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by larswmh** [comment]
As there was no further activity in this issue, we are now going to close this issue. 

---
Corona-Warn-App Open Source Team
