### ISSUE TITLE
Text issue: "verlängert" instead of "erneuert"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#907]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s / Huawei P Smart 2019
- iOS/Android version: 15.5 / 10
- App version: 2.24.1 / 2.24.2

## Describe the bug

The apps use "verlängert" instead of "erneuert" at the following places:

https://github.com/corona-warn-app/cwa-app-ios/blob/c009baf4456dd7d03ad0957eac372be392889e70/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L3368

https://github.com/corona-warn-app/cwa-app-android/blob/8dbb893ba28c899c860d10653d0f1cf1bccba0aa/Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml#L267

## Steps to reproduce the issue

1. Open the CWA
2. Click on "Certificates"
3. Click on a person with a soon expiring / already expired certificate
4. Click on the certificate which is about to expire or already expired
5. Read the text

## Expected behaviour

The app uses "erneuert" everywhere else, so I would expect to also have the word "erneuert" and not "verlängert" in this text. 

## Possible Fix

Change the text from

"Sollte dies nicht eines Ihrer aktuell verwendeten Zertifikate sein, muss es nicht verlängert werden und Sie müssen nichts weiter tun."

to

"Sollte dies nicht eines Ihrer aktuell verwendeten Zertifikate sein, muss es nicht erneuert werden und Sie müssen nichts weiter tun."

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting!

**Comment by mlenkeit** [comment]
The word _extend_ should be used in case of soon expiring certificates, whereas _renew_ should be used for certificates that were issued as 2/2 instead of 2/1.

**Comment by MikeMcC399** [comment]
@mlenkeit 

The dictionary https://dictionary.cambridge.org/dictionary/english/renew uses the word renew in a similar way to the case of expiring certificates, for example:

- I forgot to renew my season ticket
- My passport runs out next month - I must get it renewed.

A new season ticket would be identical to the previous season, except with a new date (and maybe a new price).
A passport would also be essentially identical to the previous passport, although there would usually be a new photo used.

---

You may be locked into the terms used and no longer have any flexibility, but if there is still free choice, I would use [renew](https://dictionary.cambridge.org/dictionary/english/renew) for expiring certificates and [replace](https://dictionary.cambridge.org/dictionary/english/replace) for the case of vaccination certificates which are converted to a different numbering scheme.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

For Android you have referred to the following string which uses "renew" in most places, but then, in the last sentence, it uses the term "extended":
 
`<string name="expiration_info">"If this is one of the certificates you currently use, please be sure to renew it on time. You can renew such certificates directly in the app if they will expire within the next 28 days or expired within the last 90 days, provided they were issued in Germany. In this case, the “Renew Certificates” option appears in your certificate overview, below the “Proof of Status” tile. If this is not one of the certificates you currently use, it does not have to be extended and no action is required on your part."</string>`

If I understood you correctly, you are just asking for the word "extended" in the last sentence to be changed to "renewed" for consistency with the rest of the text.

Is that correct?

In the equivalent German text, there are also two terms used: "erneuern" and "verlängern". So I suggest that this text is also reviewed for consistency, since this is less of a translation issue if the base German text also uses different terms.

`<string name="expiration_info">Wenn dies eines Ihrer aktuell verwendeten Zertifikate ist, bemühen Sie sich bitte rechtzeitig darum, es zu erneuern. Im Zeitraum von 28 Tagen vor und bis zu 90 Tagen nach Ablauf können Sie es direkt über die App erneuern lassen, sofern es in Deutschland ausgestellt wurde. Sie finden die Option \"Zertifikate erneuern\" dann in Ihrer Zertifikatsübersicht unter der Kachel \"Status-Nachweis\". Sollte dies nicht eines Ihrer aktuell verwendeten Zertifikate sein, muss es nicht verlängert werden und Sie müssen nichts weiter tun.</string>`

**Comment by Ein-Tim** [comment]
@mlenkeit 

Mh, I have a 2/2 expired certificate in the app and I have the option to "Renew Certificates". This is not the term I'd expect following your definition.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

As far as I can see, the CWA Android 2.25.0 app uses the term "renew" consistently everywhere, except in that [one place](https://github.com/corona-warn-app/cwa-app-android/blob/719f74c592c92922155acdbf19e9f6aea715b6ec/Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml#L265-L266) where it refers to "extended" at the very end of the paragraph.

**Comment by MikeMcC399** [comment]
I suggest for an Android and iOS PR to change the sentence:

"Sollte dies nicht eines Ihrer aktuell verwendeten Zertifikate sein, muss es nicht verlängert werden und Sie müssen nichts weiter tun." 

to

"Sollte dies nicht eines Ihrer aktuell verwendeten Zertifikate sein, muss es nicht erneuert werden und Sie müssen nichts weiter tun."

(verlängert => erneuert)

The text should be consistently based on the verb "erneuern" (see screenshot below).

The translation process should take care of the rest, including correcting the English text.

![image](https://user-images.githubusercontent.com/66998419/182101969-5cb88590-c0f3-4234-b30c-742da7835209.png)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

You might like to consider changing the title of this issue, since it is not a translation error. The original German text uses the word "verlängert" which has been correctly translated into "extended".

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I will adapt both the title as well as the OP of the issue later.

@mlenkeit What's your take now? Will this issue be fixed?

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this text issue to be fixed anymore. I'm therefore closing this issue.
