### ISSUE TITLE
Why is the risk tile hidden for 7 days if a positive test result is registered and not only for 5 (minimum required period of isolation)?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#908]
## Your Question
* Code: https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/src/main/resources/main-config/v2/corona-test-parameters.yaml
* Question: The app hides the risk tile for 7 days if a positive test result is registered and the risk status is low. Why does the app hide the risk tile for 7 days and not for 5 days, which is the currently minimum required period of isolation?

**Comment by dsarkar** [comment]
@Ein-Tim Will try to get an answer! Thanks.

**Comment by GisoSchroederSAP** [comment]
At time of implementation of the respective behavior, this duration was based on the [published recommendation] (https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Quarantaene/Absonderung-Archiv.html) 
Still, this disappearance was never linked to a timeframe for isolation, but was a "work-wround" in case, the user did not remove an old/expired test from the app.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP So it is not likely to change soon?

**Comment by GisoSchroederSAP** [comment]
This change in the app would require an approval of at least the RKI or even BMG. They might then aks for scientific evidence whether 5 days or 7 days (or any other duration) is the correct time frame for the app. Or they ask, why this is divergence is important now? And how many users complain? And what are consequences is the app tile id hidden 7 instead of 5 (or any other number of) days?
So, I don't think, this is likely to change soon.

**Comment by Ein-Tim** [comment]
Okay, question answered.
