### ISSUE TITLE
"Information about QR codes" screen still mentions DCC ticketing

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#915]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR / Huawei P Smart 2019
- iOS/Android version: 16.0 / 10
- App version: 2.25.0

## Describe the bug

The screen "Information about QR codes" still mentions that the CWA is able to read & process DCC ticketing QR codes. While technically that's true, I suggest to remove the information from the screen, as DCC ticketing is de facto on ice & this statement may confuse users.

## Steps to reproduce the issue

1 . Open the CWA
2. Open the UQS
3. Click on the "I" symbol
4. Read the text "Verification of your certificates during ticketing"

## Expected behaviour

There should be no mention of the DCC ticketing feature in the app. 

## Possible Fix

Remove the bullet point.

## Additional context

I offer a PR to fix this under iOS.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The ticketing feature remains in a unfinished state, with the app functionality live and the backend functionality missing. I have not seen any new statement of direction on this topic. I did notice a new PR https://github.com/corona-warn-app/cwa-app-android/pull/5430 for Android though.

In the info screen you mention there are two sections referring to ticketing and the privacy notice also contains information related to ticketing - see "Booking information" & "Verifications of certificates for ticket bookings" and other references in the privacy notice.
(app screenshot from Android follows:)

![image](https://user-images.githubusercontent.com/66998419/187064458-c445770e-4938-41d6-8a80-74551eaac947.png)

Instead of deleting the info text in the app, I suggest adding a link to the FAQ https://www.coronawarn.app/en/faq/results/#val_service_basics which I would expect to be updated if anything changes in terms of the status of the service. Alternatively the app itself could add text to say that the service is not currently available.

![image](https://user-images.githubusercontent.com/66998419/187064164-ab4e3c50-c95a-46bf-9eb0-0e799538003f.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 Adding a link to the FAQs would also be possible. I leave the decision on how to proceed from here to the team, as I don't have any strong opinions in either direction.

Have a nice Sunday!

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this informational issue to be fixed anymore. I'm therefore closing this issue.
